urbit/arvo

- arvo/hoon.hoon
> convert type printer to hoon151 syntax

- web/talk/main.css
- web/talk/main.js
- web/tree/main.css
- web/tree/main.js
fixes some tree overlay and scrolling bugs, the talk code execution bug and scroll offset bug.
talk@https://github.com/urbit/talk/commit/9f08e47a2104a5b4a352bb9ee9a37025c7d022dd
tree@https://github.com/urbit/tree/commit/cdb90fcc72f9f1d4ca6234ec16ed9e9017384762
> Frontend fixes

- web.md
- web/lib/css/bootstrap.css
- web/tree/main.css
- web/tree/main.js
tree@https://github.com/urbit/tree/commit/88abd896771460b698c905c36d8c2372e2090d4d
> Fix homepage and menu overlapping

- app/hood.hoon
- arvo/dill.hoon
- lib/kiln.hoon
Am not sure how to attach a pill to this, but it's easy to recreate.
> reset on initial pull

- arvo/ford.hoon
NB: again, not attaching a pill, but one should be built.
> Fix ford's occasional truncation of hoon files

- web/listen.hoon
- web/talk/main.js
urbit/talk@4508c54 - talk-stream
> add web/listen.hoon module for listening to comment changes

- arvo/ford.hoon
While this fixes #38, the crash therein remains (if more prettily) due to bad clay data.
> virtualize ++pact %hoon side-path

- ren/urb.hoon
Should go out when the examples repo is updated.  Later today, I expect.
> move to web/pages

- web/tree/main.js
> Load tree virtual scripts sequentially

- web/lib/js/urb.js
@ohAitch this is not coffeescript.
> fix missing braces in error handling

- app/dojo.hoon
I don't totally know what I'm doing here — but this seemed like a simple find and replace.
> moved arc to sur in dojo

- web/talk/main.css
talk@95ef0961ec4e74a5c0c61812f9c777ad07f8fd2a
This fixes the weird bug where evaluation lines aren't the right height.  Also a bunch of stuff for static components.
> Talk fixes

- sec/com/dropboxapi.hoon
- sec/com/instagram.hoon
Please let me know if there's anything else I need to do.
> added comment instructions for how to use dbox and insta security drivers

- sec/com/asana.hoon
- sec/com/digitalocean.hoon
- sec/com/dropboxapi.hoon
- sec/com/instagram.hoon
do you mind all of these commits combined into one?
> Asana driver and comments

- arvo/eyre.hoon
- children of web that start with numbers
- full beams that are partially ='d
> Minor eyre tweaks for more liberal url resolution

- arvo/ford.hoon
> Generalize ++fame to -to/ify all path elements

- arvo/clay.hoon
- arvo/ford.hoon
- arvo/zuse.hoon
- ren/tree/comments.hoon
Review by @philipcmonk requested wrt. the #39 commits not breaking anything.
> Issues 34, 39, 99, 114

- arvo/clay.hoon
> short circuit validating hoon files from ames

- arvo/eyre.hoon
- mar/urb.hoon
- mar/urb/wasp-data.js
- ren/tree/body.hoon
- ren/tree/head.hoon
- ren/tree/json.hoon
- web/tree/main.css
- web/tree/main.js
- web/tree/main_codemirror_bootstrap.css
- web/tree/main_codemirror_fonts_bootstrap.css
- web/tree/main_hoon_urb.js
- web/tree/main_urb.js
- concatenate urbit assets
- use minified resources
- preload more data
- meeker dependency handling
> Tree performance improvements

- arvo/ames.hoon
for ~ramtev-wisbyt:
<said over catholic bible>
I solemnly swear that I am Jeremy Wall and will treat this
Galaxy with the respect it deserves.
</said over catholic bible>
> Take possession of ~ped.

- arvo/ames.hoon
I'm not catholic, so no Bible for me.
> Take ownership of ~rys

- web/talk/main.css
- web/talk/main.js
- web/tree/main.css
- web/tree/main.js
- web/tree/~.codemirror_fonts_bootstrap_main.css
- web/tree/~.main_urb.js
Some fresh fixes for talk (with some minor changes to tree)
> tree@6ffed1d and talk@24e1387

- ren/tree/head.hoon
> updates :tree to serve JS/CSS assets from the current desk

- arvo/eyre.hoon
Minor fix for the login page.  And apparently my editor removes trailing whitespace.  That okay?
Fixes #45
> planet -> your-urbit

- app/talk.hoon
closes urbit#601, probably (was never able to reproduce locally)
> send line-split talk messages in same command

- web/talk/main.css
- web/talk/main.js
Fixes:
- Annoying scroll to bottom issue
- Menu appearing in correctly
- Names cutoff on hover
> talk@f6b1258

- ren/tree/head.hoon
- web/lib/js/urb.js
- web/tree/main.js
- web/tree/~.main_urb.js
urbit/tree@8fb378b
closes urbit/tree#18: 8fb378b should have been on a branch or sth until this was merged
> Add urb.init to pull /~/auth.json; call it lazily

- web/talk/main.js
> talk@d80a6c7

- lib/helm.hoon
> succesful pedantry

- web/talk/main.css
> talk@bc7b187

- web/lib/css/fonts.css
s|storage.googleapis.com/urbit-extra|media.urbit.org|g
urbit/tree@<nonexistent, this commit has been rebased>
> Update font urls to media.urbit.org

- web/tree/main.css
- web/tree/main.js
- nav flickering
- refresh comments
- don't interpret mailto: links as relative paths
- better error-handling during a scroll race condition
- warn on incomplete json preload
- timeout module unmounts, fixing back button from e.g. talk
> tree@64612ca

- arvo/hoon.hoon
> Improve random continuation in ++og

- arvo/hoon.hoon
currently `++find` / `++fand` - another potential pair is `++indx` / `++inda`...
> adds tape/list search gates

- arvo/gall.hoon
also fixes urbit/urbit#296 which is a dupe of #219
> Improve type validation in gall

- lib/write.hoon
- web/tree/main.js
And reorder the sidebar accordingly. urbit/tree@0565201
Technically I think this is only necessary on urbit-org? *continues to try to stay away from deploy*
> Use  navsort: bump  frontmatter field for posts

- lib/kiln.hoon
i've been meaning to do this every since I added `++key:by` ...
> simplifies |syncs

- arvo/eyre.hoon
... instead of hardcoding home. see #252
> serve css from the current desk

- arvo/gall.hoon
- arvo/zuse.hoon
Requires %zuse and %gall reload, which should succeed against master@219e587
@cgyarvin please review and acknowledge.
> Hack around a broken-mark subscription edge case

- app/talk.hoon
- sys/hoon.hoon
- sys/vane/ford.hoon
- sys/vane/gall.hoon
- sys/vane/jael.hoon
- sys/zuse.hoon
This changes:
=.  a  ?.  =(b c)  a  c
into:
=?  a  =(b c)  c
This also adds a few obvious changes in the vanes and in app/talk.hoon
to take advantage of this new rune.
> Add a tiswut rune which is a conditional tisdot.

- sys/vane/ames.hoon
> READ COMMIT MESSAGE

- web/talk/main.js
- web/tree/main.js
Frontend updates left over from a long time ago.
> talk@c83aedc and tree@51dbab2

- arvo/ames.hoon
(I should probably also make actual keys, but emprically this takes me months to get around to)
> ~pun + ~typ namespace grab, as a matter of public record

- ren/tree/head.hoon
(this got overwritten at some point, cherry picked from "modular-analytics" b6747f36d351e12a9a601db813b8255ed8e2cb6c)
> add support for tree head js "extras"

- sys/hoon.hoon
Includes half-precision support, removes some unnecessary code
fixes #289
> Full ++rh core, other fixes

- web/tree/main.css
Cosmetic fixes for images in posts and this: https://github.com/urbit/docs/issues/118.
> tree@258fdf7

- web/talk/main.js
This makes it possible to filter talk on a specific channel.  It's really simple, but it does work.
> simple channel filtering

- sys/zuse.hoon
fixes #357
going on the record as still baffled why there was even a conflict for the zuseflat merge to resolve
> fix bad conflict resolution in bab93e7

- app/talk.hoon
> HOTFIX disable presence reporting

- web/tree/main.js
urbit/tree@da7808a actually disable post box upon submission
> tree@da7808a actually disable post box upon submission

- gen/moon.hoon
I've seen #327 affect many new urbit users -- this seems like the simplest temporary solution.
> adds warnings and a confirmation prompt to %/gen/moon

- arvo/eyre.hoon
- lib/write.hoon
> writes web/plan to whichever desk has been |served

- lib/write.hoon
- sys/vane/eyre.hoon
> forwardport #436

- sys/zuse.hoon
> Fix small issue in ++op:dejs-soft:format when calling ++my:nl

- app/ask.hoon
- app/gh.hoon
- app/gmail.hoon
- app/twit.hoon
- gen/hood/init-auth-basic.hoon
- gen/hood/init-oauth2.hoon
- gen/hood/init-oauth2/google.hoon
- lib/basic-auth.hoon
- lib/connector.hoon
- lib/http.hoon
- lib/oauth1.hoon
- lib/oauth2.hoon
- lib/old-zuse.hoon
- sec/com/asana.hoon
- sec/com/digitalocean.hoon
- sec/com/dropboxapi.hoon
- sec/com/facebook.hoon
- sec/com/github.hoon
- sec/com/googleapis.hoon
- sec/com/instagram.hoon
- sec/com/slack.hoon
- sec/com/twitter.hoon
Went through the breach checklist and got the security drivers working, with the exception of twitter, which is broken in a non-obvious way that will require further debug work.
Most of this was zuse namespace changes, with a couple syntax errors from new hoon, and one case of requiring a new `^-` in a `|-`.
> sec/ fixes

- lib/old-zuse.hoon
Stumbled upon these missing entries while porting @asssaf's wiki.hoon to master.
> Added lore and nule

- gen/ticket.hoon
> forwardport #406 (adds error message to +ticket)

- web/tree/main.js
Fix sorting, fora locking, and twitter handle.  Not critical.  Already deployed to urbit.org, but others may want these small fixes too.
> tree@f7e376e

- sys/vane/eyre.hoon
"revert eyrelearning" didn't quite get everything
> recover SSO code from history

- app/talk.hoon
See #469.
**Apply to the network only after #469 has been applied.**
> [HOTFIX] Talk: clean up transitionary hotfix code

- web/talk/main.js
As discussed with @belisarius222.  
Matches urbit/talk#40.
> Webtalk now drops unused subscriptions.

- app/hall.hoon
- lib/hall.hoon
This goes through the new hall files and makes the doccords syntax compile.
@Fang-
> Enabled doccords in hall.

- app/hall.hoon
When messages got received they were being forwarded to subscribers regardless of whether we had already heard them or not. This change makes sure we only forward messages that actually changed. To still update the `sourced` list when appropriate, we split that off into its own delta.
(This means that circular subscriptions, like stream might want to use, no longer dos themselves.)
> Fix issues when receiving messages for the second time.

- app/ask.hoon
> send real &womb-invite's from :ask

- app/hall.hoon
- app/talk.hoon
- sur/hall.hoon
This isn't perfect[1], but it mostly enables doccords in hall and talk code. I haven't touched `%/lib/hall-json.hoon`, as the comments there are really minimal.
[1]: note the two arms in `%/app/talk.hoon` which aren't gates where I added todos about how adding doccords was leading to nest-fails.
> Enables more doccords in hall and talk.

- sys/vane/gall.hoon
> Fix gall scry

- web/talk/main.css
- web/talk/main.js
> Updates webtalk

- sys/vane/jael.hoon
- sys/zuse.hoon
Encountered some collateral damage from the keyword killing. Pretty sure this isn't supposed to be `%ktsg`.
> Reverted accidentally renamed jael tag.

- sys/hoon.hoon
Fix #95 per request to just patch it on master
> ++mold $-(* *) -> ++mold |=(* +<)

- sys/hoon.hoon
If you want these changes I'll update the Source hoons in the library docs.
> Replace $-(* *) with gate.

- sys/hoon.hoon
> Revert "updates ++boil:ap to crash if a book has pages with the same tag"

- lib/hood/drum.hoon
> fixes overflow on prompts greater than the terminal width

- .travis/.gitattributes
- .travis/package-lock.json
- .travis/runner.ls
- .travis/test.ls
- app/test.hoon
- app/test/example.md
UNODIR merging Thu 2018-4-5: touches .travis and app/test,
neither of which are used in anger on the live network.
(supercedes #691)
> test ren/ on CI

- .travis/.gitattributes
- .travis/package-lock.json
- .travis/runner.ls
- app/test.hoon
instead of just skipping building them entirely.
Also print out the failure-reasons that were previously in comments
> Check that failing :test's fail

- .travis/runner.ls
> [travis] report bail as failing test case

- .travis/pin-parent-pill-pier.url
- app/talk.hoon
- sys/hoon.hoon
- sys/vane/clay.hoon
- sys/vane/dill.hoon
- sys/zuse.hoon
forward-ports and stages #381
/cc @ohAitch
> 3-fixed (unary sample) %cnsg

- sys/vane/eyre.hoon
When you log into your urbit as many times as I do, these printf's get increasingly annoying, as the size of the stored Eyre state gets increasingly larger. If anything, I imagine users almost certainly getting confused by this.
My printf's every time I authenticate look like this:
```
[ %ses-ask
'bitnux-simsut-halmed-fossyn'
{ [p='daldes-pondex-fildut-famdex' q=[~dinwep-rochul %.n]]
[ p='ladseb-tansyp-pitmut-todseb'
q=[~poshec-migten-solrem-darryx--disnec-risrec-rivteg-daplun %.n]
]
[p='bicsum-satpel-hapdyl-rabrex' q=[~dinwep-rochul %.n]]
[ p='nodnus-batdyt-tocnum-diblep'
q=[~savsed-tinrev-bitleg-migzod--ramfur-miptyr-wacsyd-siclug %.n]
]
[p='bidrym-danter-sorred-diltus' q=[~pocwyl-soppel %.n]]
[p='rinlus-raplux-hopnec-fampur' q=[~fopnul-morlut %.n]]
[p='passyx-fipbud-tobfep-simreb' …
```
> Comment out annoying Eyre auth printf's

- lib/hood/kiln.hoon
- sys/vane/clay.hoon
- sys/vane/eyre.hoon
- sys/vane/ford.hoon
- sys/zuse.hoon
Reverts urbit/arvo#729
@eglaysher and @belisarius222 pointed out that this is a breaching change.
> Revert "Change %w care to return both @ud and @da cases"

- sys/vane/eyre.hoon
and repairs existing config in +load
> fixes bug in %eyre proxy config

- .travis.yml
Old access key stopped working, so here is a new one
> fix for travis pill generation issue

- mar/hall/action.hoon
- mar/hall/command.hoon
- mar/hall/prize.hoon
- mar/hall/rumor.hoon
> restores previously-crashing =, in &hall-action

- mar/json.hoon
- mar/txt.hoon
Some of the changes to mark conversion in ford broke some conversions, this PR just fixes one problem I encountered.
> changed json -> txt conversion to work with new mark conversion

- sys/zuse.hoon
fixes whitespace issues in #773
> adds secp jet hints

- sys/vane/clay.hoon
- tests/sys/vane/clay.hoon
Replicates https://github.com/urbit/arvo/pull/836 but without its various git snafus.
> Clay mime cache 2

- lib/old-zuse.hoon
- mar/lens/command.hoon
> adds a ^? to fix namespace issues with old-zuse

- sys/vane/ames.hoon
- sys/vane/clay.hoon
- sys/vane/dill.hoon
- sys/vane/eyre.hoon
- sys/vane/ford.hoon
- sys/vane/gall.hoon
- sys/vane/jael.hoon
- sys/zuse.hoon
Emits a %sunk note to vanes when notified that a ship has lost continuity.
> added sunk note to jael

- gen/curl-hiss.hoon
- gen/curl.hoon
- gen/dns/authority.hoon
- gen/hood/begin.hoon
- gen/hood/init-auth-basic.hoon
- gen/hood/init-oauth1.hoon
- gen/hood/init-oauth2.hoon
- gen/hood/init-oauth2/google.hoon
- gen/moon.hoon
- gen/pope.hoon
- lib/generators.hoon
- lib/sole.hoon
- sur/sole.hoon
Extracted %ask generator methods from sur/sole and put them in a core
under lib/sole
Fixed names in existing generators
> refactor %ask generators

- sys/vane/dill.hoon
- sys/vane/gall.hoon
- sys/vane/jael.hoon
- sys/zuse.hoon
- tests/sys/vane/jael.hoon
- tests/sys/zuse/dawn.hoon
Pairs with urbit/urbit#1046.  Usage described there.
Definitely take a peek at my tests, I'm not used to writing them, and I'm trying to get in the habit.
>  Allow booting from ethereum snapshot

- tests/app/acme.hoon
CI was not failing builds with failing tests -- and I pushed a failing test in #874...
> fixes :acme app tests

- .travis.yml
- .travis/print-core-backtrace.sh
so, lets just say that my planning around #879 was suboptimal ...
> [CI] fix deploy phase, move coredump backtrace to a script

- sys/vane/ames.hoon
- sys/vane/jael.hoon
these have outlived their usefulness ...
> suppress %ames/%jael printfs

- lib/ceremony.hoon
- sys/zuse.hoon
This fails CI because ingen tests don't compile.  This is annoying because it means I have to ferry pills around manually, but otherwise fine.
> change set-transfer-proxy-for to set-transfer-proxy

- .travis/pin-parent-pill-pier.url
- sys/hoon.hoon
- sys/vane/eyre.hoon
Also adds a bunch of hints to make runtime more legible.
> Use a trap to lazily evaluate the arguments to %dude in Eyre.

- sys/vane/ford.hoon
- sys/vane/gall.hoon
- tests/sys/vane/ford.hoon
> Remove our from wires

- sys/vane/ames.hoon
- sys/zuse.hoon
And removes the `%junk` task that was previously available (but unused).
> updates %ames to use provided entropy

- app/dojo.hoon
- mar/lens/command.hoon
- sys/arvo.hoon
- sys/hoon.hoon
Also removes some dead code from arvo which lets us clean up some
^ in dojo.
> Remove duplicated code between arvo and hoon

- sys/vane/behn.hoon
> Handle the move which makes the ova first

- app/talk.hoon
> Send invites to %i instead of %inbox

- app/dns.hoon
- sur/dns.hoon
Also adds DNS-provider indirection, and an initial (untested) implementation of a Cloudflare integration.
> adds exponential backoff and :hall notifications to :dns

- app/dns.hoon
maximum is the *opposite* of minimum
> on the nature of comparative quantification

- sys/arvo.hoon
> adds vane-sample type to arvo, fixes type bug in +load/+stay calls

- app/acme.hoon
- app/dns.hoon
- tests/app/acme.hoon
This should help with %pump-blocked errors.
> corrects %hiss http-request user in :acme and :dns apps

- sys/vane/jael.hoon
changed harding for performance reasons. removed some prints
> Jael prints and hards

- sys/vane/eyre.hoon
> try iterating over the right thing

- app/eth-manage.hoon
Lost this in the last qol improvement
> add %snap to eth-manage

- sys/vane/ames.hoon
> bumped ames protocol number

- app/talk.hoon
Fixes #1016.
(idk why it's under arvo internals, but we can update this as the docs evolve)
> Update talk ;help URL

- app/hood.hoon
- gen/hood/bonk.hoon
- lib/hood/helm.hoon
- sys/vane/ames.hoon
- sys/vane/gall.hoon
- sys/zuse.hoon
> release ames timer hotfix

- sys/zuse.hoon
Let's not break these, shall we?
(See also #1079.)
> Point to the correct topics when decoding Azimuth events

- sys/zuse.hoon
Does what it says on the can, nothing fancy here.
> Support eth_getBlockByNumber Ethereum RPC call

- sys/vane/eyre.hoon
- sys/zuse.hoon
Pretty bare bones, but matches the mocks.
> Landscape signin page

- sys/vane/eyre.hoon
- sys/zuse.hoon
> Revert "Landscape signin page"

- sys/vane/rver.hoon
- tests/sys/vane/rver.hoon
Some applications make multiple subscriptions to the same app on the
same path. Support this by changing the subscription interface to return
a numeric reference which needs to be passed in during the explicit
unsubscribe, and ensure that we send per-subscription instead of
per-path unsubscribe commands to Gall.
> Make %light handle multiple subscriptions on the same path.

- app/acme.hoon
- app/dns.hoon
- app/eth-watcher.hoon
- app/time.hoon
- lib/hood/helm.hoon
- lib/hood/kiln.hoon
I hadn't changed the type signature for +wake in all the apps after changing Behn's %wake +gift type.
> Fix app behn error handling

- app/acme.hoon
- app/dns.hoon
- sys/vane/rver.hoon
as discovered on the last testnet.
> lighter-than-eyre: fix small bugs in configuration and integration

- sys/hoon.hoon
#1055 part 1
test plan: +solid
part 2: remove ++hard (forthcoming)
> ;; takes spec and hoon; no more 'idempotence' test

- app/example-tapp-fetch.hoon
- app/example-tapp-subscribe.hoon
- lib/tapp.hoon
And a couple default namespace paths for inspecting the state of a tapp.
> adds explicit initialization and peek (namespace) handlers to lib/tapp

- sys/vane/gall.hoon
Fix for https://github.com/urbit/urbit/issues/1287
> joe's fix for issue #1287 in gall

- README.md
Starting to clean up contributor onboarding documentation. A first step.
> Update Contributing in README and remove Landscape info
