urbit/arvo

arvo/hoon.hoon

Limb: `^$.,.a.+>`
Old error: `[%find ~[[%.n p=1 q=[~ u=%$]] [%.n p=0 q=~] %a [%.y p=7]]]`
New error: `-find.^$.,.a.+7`

prettier find-limb errors

---

arvo/hoon.hoon

Apparently ++tack was also using ~| on wings.

---

arvo/zuse.hoon

Another victim rescued from the dicey pits of electroplating. @cgyarvin, is there a more canonical translation?

scanf was dependant on (cook :_(foo |=(...)))

---

arvo/eyre.hoon

casting to and from %hiss was failing due to occuring at a null revision

fix eyre ++back rev-0 beak

---

arvo/ford.hoon
arvo/hoon.hoon
arvo/zuse.hoon
mar/tree/comments.hoon
ren/tree/combine.hoon
ren/tree/comments.hoon

- results of dynamically executed code now cached(renderers) like it used to be (hook files)
- renderers also no longer parsed per resource path, with `/: %/foo` syntax handled by passing through "at current path, /foo" as a literal to be bound to the resource-specific path at compilation.
+ this in turn means that their compilation is largely cached, as stack trace information is no longer (mistakenly) the resource path. Fixing urbit/urbit#697.
+ tree comments have been moved to a separate renderer, isolating their /: usage
Additionally,
- jet hints throughout ford for aid in profiling
- various tweaks to ++pi-tell to make the profiler output format more readable

improve ford performance

---

arvo/hoon.hoon

- fixing unit/tree special cases
- generally show atom before cells and $% cases alphabetically

sort clauses of $fork type pretty-printing

---

arvo/ford.hoon

Which was uncovered by #113, preventing piers from booting due to a cache invalidation issue.
Closes #120, #118

Address ford cache memory leak

---

app/dojo.hoon

transmit sole-edit %nop from dojo to synchronize error positions past any %set that may have happened in the meantime

fix urbit/urbit#555

---

arvo/ames.hoon

Was thinking Douay-Rheims, but don't want to look like a fogey, so RSVCE I guess.

Take ownership of ~nym

---

app/talk.hoon

fixes an infinite loop that occurs if :talk subscriptions are cyclic

don't retransmit duplicate messages

---

lib/write.hoon
mar/plan.hoon
sur/plan/diff.hoon

Note: technically type-incompatible, might require people to recreate .plan files if they had already set a location

Use simple @t .plan location field

---

gen/moon.hoon

...when run on a non-planet ship, such as a comet.
Some of the tutorials recommend creating a moon, and just print the stack trace isn't beginner-friendly.

updates +moon to print an error message instead of a stack trace

---

arvo/hoon.hoon

The current implementation produces an "improper list" (ie, non-terminated), and requires an unusual calling convention. This version just takes a gate and applies to every item in the set (from left to right), producing a new set containing the products of the gate.
```
=+  a=(sy ~[1 2 3])
(~(run in a) |=(a/@ (gth 2 a)))
```
produces `{%.y %.n}`

fixes run:in (map over a set, producing a set)

---

lib/drum.hoon

`?=(^ old.hit)` is in there to support bootstrap, where history is presumably `~`

deduplicates dojo history (by skipping repeat entries)

---

arvo/eyre.hoon

Going to webtalk on ~tabbyn-falrud with a fakezod cookie caused repeated stack traces in the console (every thirty seconds or so).  @ohAitch gave me a fix.

fix sso crash

---

app/hood.hoon
lib/drum.hoon

Also adds implementations of meta-. and meta-backspace;  they're working (ie, tested with other keys), but commented out. Wiring them up will take changes to `dill-belt`, and the code-paths that construct instances of it. I tried changing `mar/dill/belt/hoon`, but it didn't seem to make a difference ...
Questions:
- where should the utility functions go (and how should they be named)?
- is there a better pattern to use in `++alnum`?
- what do I need to change to get meta+ backspace or `.` combinations into the `++ta-met` codepath?

adds support for meta (alt) keyboard shortcuts

---

app/talk.hoon

I was wrong about subscription reconnections not pulling a day of backlog: they used to use the last-seen message number, defaulting to 0, but this was broken by the only-pull-last-day "fix". Changed so that pull-last-day is only used in the new-station case.

Fix incremental fetching for stations already seen

---

gen/hood/cp.hoon
gen/hood/mv.hoon
lib/kiln.hoon

As a follow-up to #203, this prints the error messages *without* stacktraces.
Note: I'm passing a bunted `++toro` along with the error messages, so that I can use `++poke-kiln-info` in `hood`. That bunted `toro` is included in the move that's passed to `++emit`, so it ends up in `moz`, the `kiln` state. If that's a problem, I could add a `++poke-kiln-error` or somesuch gate that doesn't produce a `move`.

updates |cp and |mv to print errors without stacktraces

---

app/talk.hoon

In talk, when @-messages exceed 64 characters, an @ is now inserted along with the •, to ensure the next line is also an @-message.
Fixes issue #210.

Improved composing of long @-messages in talk

---

app/talk.hoon

Turns out I didn't test #211 thoroughly enough, and that the code was doing something dumb. It should now work correctly 100% of the time.

Fixed issue with automatic newline-@ for long @-messages.

---

app/time.hoon

`:time expr` roughly measures the time it takes to compute `expr`. It's a very crude approximation because it includes the time it takes the kernel and gall to parse and route a value to the app and then wait for a wakeup, but it's easy enough to get a sense of that overhead (and its variation) by running `:time ~` a few times.

:time app, measures time between poke and subsequent wakeup

---

lib/drum.hoon

I used the wrong capture semantics for the `meta-.` keyboard shortcut ...

fixes meta-. to capture to whitespace instead of by word

---

lib/drum.hoon

See #85. Not sure if this change is still desired, but it seemed like an easy fix, so here's a proposal.
Beeps if you backspace at the start of a line and it's not completely empty yet.
(Would it be appropriate to delete that comment (line 622) while I'm touching this part of the code?)

Change "backspace at start of line" to "backspace on empty line" for clear

---

app/talk.hoon
arvo/behn.hoon
arvo/hoon.hoon

This keeps the reducing gate's sample face from bleeding into the result span.
Before:
```
> (roll ~ add)
b=0
> (turn (roll ~ |=({a/* b/_(ly ~[42])} !!)) dec)
-find.i.a
```
After:
```
> (roll ~ add)
0
> (turn (roll ~ |=({a/* b/_(ly ~[42])} !!)) dec)
~[41]
```
I also did a quick grep through all existing uses of `roll` and `reel`, AFAICT the change only broke the three uses that I've updated in this PR.

Apply electroplating to roll and reel results.

---

app/dojo.hoon
app/talk.hoon
arvo/zuse.hoon

closes #208 
Crashing rejects the poke, right? (As opposed to producing `[~ +>.$]`, which would accept and acknowledge?)

reject :talk ++command pokes from foreign ships

---

arvo/hoon.hoon

before:
```
> =m (malt (limo ~[[1 2] [3 4] [5 6]]))
{[p=5 q=6] [p=1 q=2] [p=3 q=4]}
> (~(gas in *(set @)) (turn (~(tap by m)) |=({a/@ b/@} a)))
{5 1 3}
> (turn (~(tap by m)) |=({a/@ b/@} b))
~[4 2 6]
```
after:
```
> =m (malt (limo ~[[1 2] [3 4] [5 6]]))
{[p=5 q=6] [p=1 q=2] [p=3 q=4]}
> ~(key by m)
{5 1 3}
> ~(val by m)
~[4 2 6]
```
The names are overly-normal by urbit standards, but they're three letters, meaningful, and I couldn't think of urbity variants ... ;)

adds ++key:by and ++val:by

---

arvo/hoon.hoon

"gas, fail on dupe" -- as suggested in #199 ...
```
> =m (malt (limo ~[[1 2] [3 4] [5 6]]))
{[p=5 q=6] [p=1 q=2] [p=3 q=4]}
> (~(gas by m) (limo ~[[5 7]]))
{[p=5 q=7] [p=1 q=2] [p=3 q=4]}
> (~(gaf by m) (limo ~[[5 7]]))
ford: build failed ~[/g/~zod/use/dojo/~zod/inn/hand /g/~zod/use/hood/~zod/out/dojo/drum/phat/~zod/dojo /d //term/1]
```

adds +-gaf:by (non-colliding gas)

---

arvo/hoon.hoon

++peg's jet fails when `a` is 0, but the Hoon version returns nonsense. Failing seems like the right thing to do here.

Fix ++peg discrepancy with jet.

---

arvo/hoon.hoon

before:
```
> (head (limo ~[1 2 3]))
i=1
> (tail (limo ~[1 2 3]))
t=~[2 3]
```
after:
```
> (head (limo ~[1 2 3]))
1
> (tail (limo ~[1 2 3]))
~[2 3]
```

electroplates ++head and ++tail

---

arvo/hoon.hoon

Before:
```
> =+(a=42 ^~(a))
0
> =+(a=[1 2] ^~(a))
[0 0]
```
After:
```
> =+(a=42 ^~(a))
42
> =+(a=[1 2] ^~(a))
[1 2]
```
I was bracing for this to have a noticeable performance impact, but it actually seemed to improve `+solid` times by 10-20%. (With the corresponding jetted version of course, the Hoon code never actually runs.)

Prevent ++burn:ut from zeroing non-constants.

---

arvo/clay.hoon

#238 caused `(cury same %&)` to lose its meaning, so this desugars the instances of it in clay.hoon.
@juped, can we get this merged quickly?  Master is currently broken.

remove broken sugar

---

lib/womb.hoon

since the read-only mode is no longer the sensible default

re-enable %womb ticketing and recycling

---

arvo/eyre.hoon
web/robots.txt

Upon review, /robots.txt is actually a magic web filename, which shouldn't interact with the tree frontend etc.
This PR keep the config change from "DENY" to "ALLOW"

Put robots.txt back in eyre :/

---

lib/drum.hoon

advance apologies for the opening this massive PR without warning ...
I started refactoring as I looked into #255. I ended up blocked there, but some of my changes seemed generally useful. I kept them, and started on a long-overdue cleanup of `++ta-met` and related gates. I've tried to keep my commits separate, but I'm happy to cherry-pick across multiple branches if that'd be easier to review.
This PR covers several areas:
- restoring lost PRs
restores the fixes from #226 and #235 (although not their exact implementations), which were inadvertently removed in 786bce0
- dead code removal
everything related to `++master`, `++ukase`, and several `++se-*` arms were completely unused
- type safety
favoring `?=` over `.=`, avoiding `-.limb`, especially when pattern-matching a kelp, casting …

refactors drum

---

web/talk/main.js

Selecting previous messages' audiences would result in ~~him/foo messages, which would promptly be rejected by the server.

urbit/talk@c83aedc Don't prepend extra ~ to audi

---

ren/tree/head.hoon

Usage: e.g. ren/tree/head/extras/analytics.js containing
```
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
ga('create', 'UA-47054188-3', 'auto');
ga('send', 'pageview');
```

add support for tree head js "extras"

---

app/talk.hoon

Talk no longer displays @ as the glyph for your own @-messages.

---

app/hood.hoon
arvo/dill.hoon
arvo/zuse.hoon
lib/drum.hoon
sur/sole.hoon

This PR implements the molds and transformations discussed in #212...
It's not ready to be merged -- right now it styled dill-blits are slogged, and then output with the styles stripped. I opened it now so the molds and overall approach could be reviewed early. 
questions:
- should the core in `drum:ta-klr` be moved somewhere else? A "klr-engine" in zuse?
- right now, lines are hard-wrapped at the terminal width -- should I be wrapping at the previous word boundary? (I haven't taken the time to deconstruct `++re` yet ...)
I'll get started on the actual color printing in `term.c` now ...
Examples:
```
=/  klr/styx  ~[[```%r "foo"] [```%g "bar"] [```%b "baz"]]
[[ost %diff %sole-effect %klr klr]~ +>.$]
```
`dill` slogs
```
[[p={} q=[p=~ q=%r]] "foo"]
[[p={} q=[p=~ q=%g]] "bar"]
[[p={} q=[p=~ …

adds styled text molds to ++dill-blit and ++sole-effect

---

arvo/eyre.hoon
arvo/hoon.hoon
arvo/zuse.hoon
lib/down-jet/parse.hoon
lib/oauth1.hoon
lib/react.hoon

While this isn't much of a win for the existing code, I think it's a big win for end-users. The "automatic `crip`" behavior is pretty counterintuitive, at least to me.
Also, `|=(a/tape (crip (cass a)))` could be `(corl crip cass)`, if not for the onerous "span check" in `++corl`.

updates ++cass and ++cuss to return a tape instead of a cord

---

arvo/hoon.hoon

*apologizes for this and all future attempted cleverness*
I thought `++by` and `++in` used the same hashes, but I only checked atoms ...
closes #266

fixes +-key:by (produce a valid set by using +-put:in)

---

arvo/dill.hoon
arvo/hoon.hoon
arvo/zuse.hoon

as reported in #199 and urbit/urbit#622
This PR doesn't disallow duplicate arms, but simply removes those that already exist (since the disallowing has to be released separately).
Note: I renamed `++hump` to `++hemp` instead of removing it. It's unused, but so is much of the surrounding code in Section 2eP...

remove duplicate arms within kernel cores

---

arvo/hoon.hoon

The current `+-gaf:by` implementation prints `%duplicate-key` for every recursive invocation prior to detecting a duplicate.
There's still a bigger problem, which is that wet arms can't `++slog` in a type-aware manner (see urbit/urbit#700). Given that, and the inapplicability of `+-gaf:by` to #199, is it worth keeping around? Should I instead just remove the arm?

removes +-gaf:by

---

arvo/hoon.hoon

I'm not sure that this is the most efficient approach. It maintains lists of ancestor nodes: `l` for ancestors whose left branch we descended, `r` for right. (there's a case to be made for reversing those names ...)
In any case, using the broken `+-key:by` implementation:
```
:+  (apt (sy /a /b /c ~))
(apt ~(key by (my [/a 1] [/b 2] [/c 3] ~)))
(apt (sy /a /b /c /d /e /f ~))
```
produces `[%.y %.n %.y]`
re #266

updates ++apt to transitively verify set constraints

---

arvo/hoon.hoon

as pointed out by @ohAitch on `urbit-meta` ...

updates ++snag to cast the product

---

lib/elem-to-react-json.hoon

this change from #262 that was lost in the merge of #287

reapplies ++cass change too lib/elem-to-react (unbreak the web)

---

arvo/hoon.hoon

added this now that #270 has been merged -- see #199 for discussion.
closes #199

disallows duplicate arms in ++wisp

---

gen/pope.hoon

Curve key generation is fast enough that computing all the partial-passphrase keys is not prohibitively expensive.

remove [press enter to compute] +pope prompt

---

app/talk.hoon

`;set mutegroup` suppresses group notifications (ie `for station --met ship %hear`).
I'm fairly sure this doesn't break anything. `;who`'s output still updates correctly at least. Please do verify.
Also, I'm taking suggestions for a better setting name than `mutegroup`. `mutepresence` seems a bit long, `quiet` too ambiguous. What do you think?

Added a %mutegroup setting to talk. Suppresses presence output when set.

---

sys/hoon.hoon

also renames `+-ept:by` to `+-apt:by`, and simplifies `++qeu`.
my branch was created on top of cgyarvin/cc-merge. Should I reparent these commits somewhere else?

applies map/set invariants inside the molds

---

app/talk.hoon

Added the `%notify` flag. Having called `;set notify`, the terminal beeps whenever a message contains the first part (`~palfun`) of your ship name.  
Magically, it doesn't beep for your own messages.
Contains the telegram renderer core modification that's also included in #308.
Would love a code review on this (lines 440-449). I saw vaguely similar constructions in the rest of the code, but I'm still unsure if this is "good" Hoon or over-engineering. Let me know!

Talk setting: notify on mention

---

arvo/ford.hoon

This will cause many false positives (all apps reloaded on any mark change), but @cgyarvin says it's better than them drifting out of sync as they currently do.

add /===/mar and /===/arvo to %core req dependends

---

arvo/ford.hoon
mar/json.hoon
ren/rss-xml.hoon
ren/tree/head.hoon
ren/urb/tree.hoon

All rss source items must now have title: and description: markdown frontmatter to display properly in readers.

Change .rss-xml to use correct urls, metadata

---

app/talk.hoon

Now properly parses `;who station` and denies `;whostation`.
This fixes urbit/talk#29.

Fixed talk's parsing of ;who

---

app/talk.hoon

Added the `%showtime` flag. After calling `;set showtime`, timestamps appear to the far right of messages, much like in webtalk. Unlike webtalk, this can't correct for the user's timezone.  
Requires a terminal of at least 90 characters wide for comfy displaying.
Modified the telegram renderer core `tr` a little bit. Instead of passing the `%noob` flag, we now pass the entire list of flags. `sef` for **se**ttings **f**lags.
I felt like giving `:talk` a little loving. Personally like seeing timestamps in my chats, and webtalk already has them, so why not. It's opt-in too, so talk remains 80 lines wide by default.

Talk setting: message timestamps

---

arvo/gall.hoon

Leaves in ap-blocking-misvale because that's an actual error

remove mo-defer and mo-resume printfs

---

sys/vane/clay.hoon
sys/zuse.hoon

This is just a first pass -- here's what it looks like:
```
> .^((set desk) %cd /===)
{%base %kids %home}
```
Some questions:
- Should there be an arm for `(set desk)` to make the `.^` simpler?
- Should it produce something other than a set?
- And what should the mark in the cage be?
- Is there any reason that `++take-foreign-update` can't just ignore `%d`?

adds scry-desks feature to %clay (care %d)

---

lib/elem-to-react-json.hoon

I added these a forever ago with plans on making the library docs self-explaining, but never did that for a number of reasons (speed, looks, %eyre going insane and breaking which I could never track down...)
I'm, uh, mildly concerned that this is still here. Because `slap`, although purely functional, doesn't time out Nock evaluations. And everything that is posted to `:tree`, including third-party content, is ran through this. You can connect the dots.

Remove <urb:pre> tags

---

mar/talk/telegrams.hoon

thereby fixing `:talk|save %porch`
this works on maint-20160818 as well

handles $mor speech in mar/talk/telegram

---

app/talk.hoon

Before going through with a `%publish` command, checks whether source of the poke is in our `++team`.  
(We don't crash/throw an error because we don't want to bother the user with the useless efforts of whoever is trying to be malicious.)
Solves #208. I believe this is the fix #221 was looking for.
Authorized messages to and from ships and their channels seem to still function fine with this change. I believe I'm catching the right case in the right part of the code here, but as always it'd be cool if someone could verify.

Prevent unauthorized talk message sending.

---

mar/html.hoon

Fixes issue where ford doesn’t know which of two diffed html files to
build.

Add `++  grad  %mime` to html.hoon mark.

---

web/lib/js/urb.js

Posting links to `comet--name.urbit.org` via webtalk causes it to post as a regular line, possibly breaking up. Turns out this is because of the `--`, which urb.util.isURL doesn't recognize as valid.
This change allows any number of successive hyphens. I couldn't find any evidence this isn't allowed in either subdomains or domain names (but maybe I'm looking in the wrong places?).

Fixed urb.util.isURL to allow multiple successive hyphens in URLs.

---

lib/drum.hoon

This is just a forward port of #360. Due to #357, I'm unable to test it. Instead I was able to test this:
https://github.com/urbit/arvo/compare/4288aab089c46cc9fb575c37e393137f6ec339f6...joemfb:prompt-sticky-tmp
As best I can tell, the only difference is `:^dill` vs `:dill` ...

forwardport #360

---

sys/hoon.hoon

This supersedes #343 (at least, temporarily). Should that be closed, and instead tracked in an issue?

prevents unsafe $cork (|^) expansion in the parser

---

sys/hoon.hoon

`++hard` doesn't have this problem, since it's wet.
before:
```
> ((hard (list @)) [0 1 2 3 4 0])
~[0 1 2 3 4]
> ;;((list @) [0 1 2 3 4 0])
nest-fail
```
after:
```
> ((hard (list @)) [0 1 2 3 4 0])
~[0 1 2 3 4]
> ;;((list @) [0 1 2 3 4 0])
~[0 1 2 3 4]
```

prevents nest-fail in ;; / :fry

---

arvo/dill.hoon
arvo/eyre.hoon
arvo/gall.hoon
arvo/zuse.hoon

Supercedes #378
In addition to adding remote %peel, this reverts %gall handling of foreign diff results to an earlier version, which incorrectly translates the data using the desk of the local app with the same name. This is caused by an arvo limitation, which necessitates ames negative ackgnolwedgments be given explicitly instead of being generated from a crash.

Enable js urb.bind to a foreign {ship}: v2

---

lib/drum.hoon

In my perpetual quest for bite-sized pieces of work, I stumbled on #18. Seemed easy enough, so I dove in, with the additional goal of adding truncation markers where appropriate. That led me down a rabbit-hole resulting in https://github.com/joemfb/arvo/tree/prompt-ellipses, which correctly adds ellipses, but doesn't truncate. I had to basically bruteforce the solution, since `term.c` does some weird things with the cursor based on the buffer length (and those seem to interact poorly with the constantly-refreshing approach ...). My conflicted inclination to rewrite term.c intensifies ...
So I switched back to the original task. 
To have a stable, sticky input window, you have to know how long the prompt is. Once you're there, it really makes sense to make the prompt itself sticky - the …

adds sticky prompt scrolling

---

arvo/hoon.hoon

This functioned fine when it was originally implemented but, you know, wet gates.

Fixed ++oust to not require faces for [a b].

---

arvo/gall.hoon

`%gall` was unnecessarily specializing diff types.

%gall diff spec fix

---

sys/hoon.hoon

Especially with the advent of `=,`, there isn't a reason for these libraries to contain all of the stdlib. This leads to footguns and people asking in urbit-meta why `(add:si --1 --1)` doesn't work like it should.
I did a `grep -r ":si"` and all the uses look unaffected, and I can boot a fakezod and `|reset` just fine.
(Unfortunately, there goes a couple of my codegolf entries...)

Don't shadow stdlib in libraries

---

mar/noun.hoon

Fixes an issue where trivial moves to ++poke-noun app arms across ships
wouldn't resolve, and ++coup in those apps would throw away the stack
trace.
See this Fora post:
<http://urbit.org/fora/posts/~2017.5.30..04.45.41..dbd2~/>
Edit: The ++coup thing is unrelated, @ohAitch explained to me.

Add minimal noun.hoon mark to /mar

---

gen/ticket.hoon

This is another frequent question on `urbit-meta` -- the current error message ("blocking not care: ~.a") is both wrong and unhelpful.

adds error message to +ticket

---

web/talk/main.js

It does seem to be the case that %fat messages aren't printed neatly. They overlap with the text below them, like fora post contents used to do.
At least webtalk loads again. (Though a lack of "how do I render this message" shouldn't cause the entire web app to not function. Oh well, it'll get better Soon™.)

Fixed rendered of %app and %lin speeches in %fat.

---

mar/plan.hoon

So you can display your username in its canonical capitalization. Also, you can now put crypto addresses in there!
The new `++knot` parser is essentially a simplified `++urs:ab` with `hig` added in.
Is this all it takes? `'UserName'` fits in `@ta` and `@tx` just fine, nothing seems to be complaining, and this renders just fine.
(I'm having trouble doing rigorous testing of `mar/plan` from dojo, but since the changed path also gets covered by loading the profile page, I'm not too worried.)

Allow capitals in web.plan usernames.

---

app/dojo.hoon

Trim any trailing spaces on the line. fixes #430

Trim any trailing spaces from lines in dojo

---

lib/oauth2.hoon

This adds an `Accept: application/json` header to hisses sent from lib/oauth2 and is a solution to urbit/arvo#442. 
The OAuth2 library, as it is currently implemented, requires a JSON response from a service to parse the access token correctly. For this reason, I have added the `Accept: application/json` header to the `++post-quay` arm, as this arm is already used for adding the `Content-Type` header. Without this `Accept` header, some OAuth2 APIs respond with non-JSON formats by default, which the current lib/oauth2 is not prepared to handle, therefore resulting in a `%bad-json` error (see urbit/arvo#442 for more details). 
1. I've combined *running* and *3-fixed* [forms](http://urbit.org/docs/hoon/syntax/). Is this considered undesirable, in which case I should stick with either/or?
2. …

Added 'Accept: application/json' hiss header to lib/oauth2

---

sys/vane/gall.hoon

Apparently gall wasn't actually removing subscriptions from `sup.ged` (and this `sup.bowl`) after killing them with `%quit`.
To reproduce that:
1. Load [this paste](https://pastebin.com/eS7xfNMi) into a fakezod and a star (say, ~palzod), `|start %test`,
2. On ~palzod, `:test [%sub ~zod]`,
3. On ~zod, `:test [%update ~palzod]`, ~palzod should say `%got-diff`,
4. On ~zod, `:test [%quit ~palzod]`, ~palzod should say `%quit-by`,
5. On ~zod, `:test [%update ~palzod]` again, it should still say `%got-diff`.
All this change does is remove the affected subscription from `sup.ged` in gall's state whenever a `%quit` move gets sent.
I don't think anything has to change on the receiving end, since `++quit` gets called properly, and outgoing subscriptions aren't tracked yet. (Considering how simple a …

Remove registered subscription from gall when sending %quit.

---

arvo/ford.hoon

`/+` and `/-` are supposed to be able to parse ship and case, but the parsing was broken. Docs for this behavior are part of [this docs PR](https://github.com/urbit/docs/pull/192), which should be merged after this PR is merged.

Fix ford ship and case parsing

---

sys/hoon.hoon

see #361 for discussion
I had to comment out the `1-d` assertion in `gen/metal` to make a pill from this. I've uploaded it here: https://www.dropbox.com/s/2nz4w5cxdwjqqmo/door-aliases.pill?dl=0
Here's my test case:
```
|=  arg/@
=<  abet:(~(flub . 10) arg)
|/  a/@
+*  this  .
samp  +<
cont  +>
++  abet  [~ a]
++  flub
|=  b/@
?>  =(a samp)
?>  =(+>+>.$ cont)
this(a (add a b))
--
```
How should I format the `$door` page to preserve the margin?
Also, there are duplicate `:door` keyword declarations, along with both the `|_` and `|/` runes. Should the keywords be deduplicated? And can `|/` be removed?
closes #361

adds optional %tstr aliases prelude to %brcb

---

app/talk.hoon

People who are now joining `urbit-meta` are finding that new messages won't render.
What's happening is that a large amount of messages sent to the client causes that subscription to be dropped for some reason, even though it's an internal one. Unfortunately, talk doesn't have ++quit arms to resubscribe in such a scenario, so it stays disconnected from hall, never receiving new messages.
This PR implements the fix, and forces existing talk instances to resubscribe to hall.  
A follow-up PR will be posted shortly to clean up some of that "transitionary" code. **When applying these two PRs to the network, please put them live sequentially,** and not both at once.

[HOTFIX] Talk: implement ++quit arms

---

app/hall.hoon

As it turns out, the `count` of some stories got out of sync with their `(lent grams)`. Because `count` is relied on for message fetching in a number of different ways, this resulted in unexpected behavior in a number of place, including webtalk loading only a partial backlog, and ;join-ing urbit-meta giving you a similar scrollback.
Notice that this is just a small addition to `++prep` that resets `count` to `(lent grams)`, and doesn't actually address the cause of `count` getting out of sync.  
This is because I genuinely have no idea how it could end up in an incorrect state. There is [only one place](https://github.com/urbit/arvo/blob/master/app/hall.hoon#L1585-L1590) where new messages get appended to `grams`, and it obediently increments `count`. I also haven't been able to …

[hotfix] Reload message counts that got out of sync

---

app/hall.hoon
web/talk/main.js

Apparently converting a large json list of objects into  json string makes eyre unhappy.
This contains two fixes:
1. Makes sure that grams aren't sent for subscriptions that don't explicitly request them. This oversight was causing webtalk's `/config-l/group-l/0` request to also include all messages starting at #0.
2. Changes to webtalk that make it do slightly more modest requests. See urbit/talk#38.

Fix backlog loading/eyre dig over issue with webtalk

---

app/hall.hoon

Currently, hall doesn't check to make sure that diffs it gets via a %present command, or a %status or %config rumor have any effect. This can lead to diffs being spread around to subscribers when nothing has actually changed.
This implements checks for catching those scenarios, and ignores the diff when they occur.

Fix erroneous presence handling

---

app/hall.hoon
app/talk.hoon

In my haste to get #471 out the door, I completely overlooked the fact that other parts of state are set using `count`. This means that, for however long halls were running with incorrect `count`s, they accumulated incorrect references to messages. This (0e04242) performs a slightly more involved version of what #471 did, rebuilding `known` and `sourced` as well.  
(Note that `sourced` sadly can't be recreated with 100% certainty, but the approximation we do instead should be accurate for all but some rare edge cases. This is not a big deal, because nothing currently depends on it.)
Additionally, logic for updating existing messages was replacing the wrong message due to an off-by-one error. This includes a fix for that.
I've also included a `++poke-noun` arm in both hall and talk. Doing …

Rebuild msg number references, fix msg updating, provide debug tools

---

app/hall.hoon
app/talk.hoon

Couple tiny things.
- Properly sanitize "nested" messages, like replies and messages with attachments.
- Print circle description and message sanitizing rules on-join.
- Don't send presence when a non-default subscription occurs (as a result of `;source`).
- Slightly more adaptive rendering for informational messages, like presence notifications.

Hall & talk QoL fixes

---

app/hall.hoon

Hall's `++prep` no longer performs any cleaning whatsoever.
Now that #481 has gone onto the network, everyone's halls should be in a sane state again. Bringing `++prep` back to baseline prevents `sourced` data from being overwritten with potentially incorrect guesses if hall gets modified in the future. The debug tools introduced in #481 still allow the user to run the from `++prep` removed code if necessary.

Revert hall's ++prep back to normal.

---

sys/hoon.hoon

having been bound they'll stay bound, but these seem less crucial,
being mostly called from already inside the other compiler jets

picked up a few more mis-replaced jet hints

---

app/hall.hoon

For some reason this was only now giving runtime errors for some.
Related to #447.

Work around runtime error caused by _example behavior.

---

app/talk.hoon

This really should've been included in #487. It's not as necessary here, but still good to get it back to baseline.

Remove old hall susbcriptions in talk's ++prep

---

app/hall.hoon
app/talk.hoon
sys/vane/ames.hoon

Bunch of fixes for subscriptions, and some higher ease-of-use for circle sources.
- `++quit` now always tries to re-subscribe. (Turns out gall doesn't do that for you.)
- Subscription (and poke) fails get handled more gracefully.
- Improved sources tracking for circles.
- `;join` loads a single day of backlog by default (rather than everything).
- `;leave` unsubscribes the inbox from _all_ related sources.
- Command for inspecting sources of circles. `;sources %whatever`
Also makes talk force-reconnect to hall on update (people got unlinked again somehow?), and includes more debug poke options/actions.

Hall & talk: subs & sources

---

app/talk.hoon

Okay now it's just getting embarrassing.
Fixed an issue where talk, upon hearing a message it had already heard, tried to "revise" it by just deleting it from the messages list and... doing nothing else.
Since that means hall's local copy of the inbox can't be trusted to be any kind of coherent anymore, the ++prep cleans it out, causing it to be rebuilt from the hall re-sub that was still there.  
This will cause everyone's backlog to be printed all over again, but that's just local load. (We'll definitely want to push out a clean ++prep after we've confirmed this fixes people's issues though.)
Closes #497, and should take care of #501, hopefully. This resolves the stack trace that was being thrown there, so if that's what's blocking it, this clears that up.

Make talk actually revise reheard messages

---

app/hall.hoon

Creating `/app/hall/filter.hoon` allows you to modify messages before storing & resending them.
Intended to be used by stream for audience fixing. If we don't want to manually define the web ship's name in there, we may want to modify this to accept additional arguments. Maybe just the entire `bowl`. If that's desired, let me know and I'll put that in before getting this merged.

Customizable filter for incoming hall messages

---

app/talk.hoon

So that it doesn't reload everyone's backlog the next time it gets updated.
Also adds debug pokes for doing the reset ++prep included and a trigger for a legacy issue.

Reset talk's ++prep

---

lib/gh-parse.hoon
mar/gh/commit.hoon
mar/gh/issue.hoon
mar/gh/repository.hoon
sur/gh.hoon

Can now take in commit and repository data.  
Issue data can now be extracted directly from a `httr`.

Expanded on existing Github marks

---

app/hall.hoon

Turns out always sending the full scrollback isn't a good idea, considering resubscribes can happen at any time.
This makes sure only the last 2000 messages get shared.
Not entirely sure if this will take care of the cases ~marzod and ~samzod are experiencing, since they crashed in a state where they're trying to process a received package. Will have to swap the printf out for a truncation of `gaz` if that's the case.

Federation performance hotfix

---

app/hall.hoon

No longer incorrectly uses the subscriber's ship name when getting the affected story.
(The real fix is the change from `who.qer` to `nom.det` on line 2328. The rest is just cleanup and comments to make this block easier to follow, since it had me struggling for a little while when revisiting it just now.)
cc @c-johnson

Fixed weird code for updating /circles subscriptions.

---

sys/vane/gall.hoon

Maybe not ready for merging. Want to get a PR up for further discussion.
Apps that send `%peer` moves with bone 0 can get in trouble for that. When gall tries to kill the subscription (because some error occurred because of it) it tries to get at bone 0, but by its own rules, this isn't allowed.  
Considering bone 0 means "no cause", that's fair. Everything an app does has a cause. At the very least, that is "app was booted".
This change rejects moves that use bone 0, giving the same error message that is used for unknown bones. (And it technically is, because 0 only ever has empty ducts associated with it for some reason.)
An alternative approach saw [this line](https://github.com/urbit/arvo/blob/master/sys/vane/gall.hoon#L600) changed to set a 0 bone to be the bone that was used for …

Prevent gall from breaking things over bone 0

---

sys/vane/clay.hoon
sys/zuse.hoon

This is the simplest possible implementation of a %next for multiple simultaneous files.  
If the subscription includes files in the past, or on other ships, then it is ended immediately. If one or more of the watched files change, then all those changes are sent in one response.
Not yet ready for merge. Lobes currently [aren't dealt with at all](https://github.com/Fang-/arvo/blob/afb1836f4477c8f35d5bc862efa3a1926354a8b3/sys/vane/clay.hoon#L604), as I'm not entirely sure how to do that here. It appears as if `++blab` calls out to ford to build the file into data for us, which won't happen for our restricted set of supported cases. Correct y/n?
(Also I should maybe change existing uses of `(unit (each cage lobe))` into `cach` (and probably rename that into like re`sult` or something), for …

Clay multi-%next: %mult (and fix for %next)

---

sys/vane/ames.hoon

Also put on an n in compliance with current Steven Dee naming
conventions (and various government IDs.)

New key for ~tyr

---

sys/vane/clay.hoon
sys/zuse.hoon

As suggested by @ohAitch in #575, the interface for `%mult` now allows you to set a care *per path* rather than for all the paths in the request.
Also removes needless `++gift` mirror from its internal structures.

Clay %mult multiple cares

---

app/hall.hoon
app/talk.hoon

Gall disallows it since #538. Did a quick search, found no other offenders.

Hall and talk no longer use bone 0

---

app/hood.hoon
gen/hood/private.hoon
gen/hood/public.hoon
lib/hood/kiln.hoon
sys/vane/clay.hoon
sys/vane/dill.hoon
sys/vane/ford.hoon
sys/vane/gall.hoon
sys/zuse.hoon

As discussed internally, permissions for the filesystem.
Permissions are set for all revisions of a node. If a node doesn't have permissions set, those of the parent node are used. If no permissions are set all the way up to root, we default to fully private.
The clay interface sees some additions to support basic permissions management.
`++task`:
- `{$cred our/ship nom/@ta cew/crew}` for setting permission groups.
- `{$crew our/ship}` for getting permission groups.
- `{$perm our/ship des/desk pax/path rit/rite}` for setting permissions for a node.
- A `%p` `++care` for reading permissions set for a node on a local desk.
`++gift`:
- `{$cruz cez/(map @ta crew)}`, the response to `%crew` requests.
- `{$rule red/dict wit/dict}`, the response to `%p` file requests.
~And a notable change that …

Clay permissions

---

sys/hoon.hoon
sys/zuse.hoon

I've only tested this in a generator -- I can't find a recent commit of master that lets me `|reset` ...
closes #296

updates ++boil:ap to crash if a book has pages with the same tag

---

sys/hoon.hoon

After looking at `++pair` I agree with Anton that these should be `++mold`.
All of the vanes compile with these changes.

Use ++mold instead of ++gate in ++cask and ++hypo.

---

lib/hood/kiln.hoon

Ensures that updating live to current master doesn't kill the kiln. As suggested [here](https://github.com/urbit/arvo/pull/610#issuecomment-365730101).
These should be removed once an update has actually happened, but are safe to stay in until any of the involved structures change.

Update crutch for kiln

---

app/twit.hoon
gen/twit/as.hoon
gen/twit/feed.hoon
lib/oauth1.hoon
lib/twitter.hoon

I finally got around to trying out `:twit`. The `++peek` interface was out-of-date*, as were the `|as` and `|feed` generators.
\* The `care` is now passed as part of the path, and the last path segment is ignored (presumed to be a mark?).
I had another problem trying to post: the negotiated access token was read-only and couldn't be upgraded. I created a new read-write access token, but can figure out how to get %eyre to stop using the old one. Is there currently a way to manually configure (or force a request for) a new token?
I also deleted the github driver config.

some changes to get :twit working

---

app/hall.hoon
app/talk.hoon
lib/hall-json.hoon
lib/hall.hoon
mar/hall/action.hoon
sur/hall.hoon

These changes were requested for the current work on a new web UI. In particular, these will allow the client to deal with DM groups more elegantly.
- Adds a `tag/(set @ta)` "usage tags" to circle configuration, which clients can use so store arbitrary usage metadata.
- To set these during creation, issue a `%design` action, which creates a circle with the specified `config` structure.
- To change these for existing circles, use a `%usage` actions to add or remove any number of tags.
- When updating permissions, `%inv`ite messages are no longer sent automatically. The client can decide when it is and isn't appropriate to send these itself. Closes #606.
cc @c-johnson @vvisigoth

Hall additions and changes to support New Web DMs

---

sys/hoon.hoon

Guess we should've waited for the CI check on #417 after all.

Fix outdated use of "span" in hoon.hoon

---

app/hall.hoon
app/talk.hoon

There was a bug with circle deletion after all.
Due to how `++pull` was implemented for circles, pulling a subscription to a deleted circle caused a circle to implicitly be re-created under that name. Now does a check to make sure we still have the circle that needs to hear the change before trying to apply the change.
Also, the `++prep`s of hall and talk were making me a bit uneasy, so I updated them to do state versioning. This way, nobody has to worry about `++prep` when making changes to hall and talk unless they're changing their states.  
The `++prep` in talk is a bit weird because its state starts with a `@ud` which we can't distinguish from the `@tas` tag of versioned state. People with exactly one message in their talk's `count` lose state with this. Taking suggestions if anyone …

Hall circle deletion bugfix and ++prep improvement

---

app/hall.hoon
app/talk.hoon
lib/hall-json.hoon
lib/hall.hoon
mar/hall/action.hoon
sur/hall.hoon

The stars are currently drowning in `%diff-bad-ack` messages. They're trying to send out urbit-meta updates so subscribers, but not all of those subscribers are running the latest arvo with the recent hall changes. This results in a mismatch in the expected message type.
In its current state, the network clearly isn't ready to receive userspace protocol updates. Not all ships are getting/running updates (see also #509 and #611), and comets weren't in the first place. There is currently no mechanism for implementing application interface versioning that would allow this to be overcome elegantly, so I think our safest bet here is to just keep interfaces consistent for now.
The changes this reverts come from #621. These were made to support the currently still in development Collections …

Revert changes to hall circle configs (and thus the hall protocol)

---

app/hall.hoon
app/talk.hoon
lib/hall-json.hoon
lib/hall.hoon
lib/hood/kiln.hoon
mar/hall/action.hoon
sur/hall.hoon
sys/vane/clay.hoon
sys/vane/dill.hoon
sys/vane/eyre.hoon
sys/vane/ford.hoon
sys/vane/gall.hoon

- Make federation more performant by just sending 100 messages of backlog initially. (short-term fix for #582 in a federation context)
- Put #621 back in.
- Clean up app (hall, talk) and vane (clay, dill, eyre, ford, gall) states and state adapters to be state version `%0` again.
- Remove deprecated code in kiln.

Pre-breach cleanup

---

sys/vane/ames.hoon

Also removes trailing whitespace from ames, something we really should do for the whole repo sometime.

Bump ames version for breach

---

app/talk.hoon

Makes moons suffer less when connecting to old planets.
Had this queued up for a while, apparently never made it into a PR.

Talk now only loads in messages from the last five days on first boot.

---

sys/hoon.hoon

This should fix womb, which has a |=(mold (unit (... +<))) that
pulls ++unit from the wrong place.

amend #589 to reduce =| mold namespace pollution

---

gen/moon.hoon

Removes warning and confirmation dialog.  
Also pretties up the result printing a little bit, from:
```
moon: ~etc; ticket: ~etc
```
to:
```
moon: ~etc
ticket: ~etc
```
cc @keatondunsford

Remove outdated warning message about moons

---

sys/zuse.hoon
tests/zuse/crypto/keccak.hoon

This implements the keccak family of hashing functions (keccak, sha3 (FIPS 202), shake and rawshake). These are required for my ongoing Ethereum integration, but are worth their own PR.
Invoke as such:
```
=,  keccak:crypto
=/  input-a=@  (swp 3 'some string')
=/  input-b=@  0xabcd.1234
(keccak-256 input-a)
(sha3-512 input-b)
(shake-128 256 input-a)
(rawshake-224 64 input-b)
::  outputs, in order, cast from @ to @ux:
::  0x83c7.37ad.570e.9f3e.71e0.d280.0958.e447.70d8.12e9.2db2.c175.8626.613d.1e6b.a514
::  0x1cae.3332.3396.c8d7.ddb8.cfbb.3d86.b66f.2273.fe62.0f8a.2d9f.869a.b6ca.cdae.a4cb.4669.b080.f3d4.bb80.71e0.4630.7d8a.ce9b.87ee.bd9a.1391.4d08.7d04.10ea.ed12.eae6
::  0x971d.f044.e825.bed0.dcbe.0650.342d.ebab.1732.5fe0.bd41.16a4.3b8b.388d.44cf.5e34
::  0x9dd2.45ee.bef0.e9a3
```
Shake has …

Add keccak hashing family into zuse

---

gen/test.hoon

My expectation was that this is how it worked, because the testing documentation mentions that testing arms start with `++test-` (or `++check`, not sure why). This isn't the case though, as adding a `++helper` into the main core causes it to try running that as a test anyway and crashing.
This PR makes sure that only arms starting with `++test-` are actually run when doing tests.

Make +test only run arms starting with ++test-

---

gen/test.hoon
lib/tester.hoon
tests/new-hoon/ls.hoon
tests/new-hoon/mp.hoon
tests/new-hoon/myb.hoon
tests/new-hoon/thr.hoon
tests/zuse/crypto/keccak.hoon

- clean up interface, pretty-print bug
- speed up by avoiding half a second of per-test compilation, instead doing it up front where the cache works

clean up and accelerate +test framework

---

app/hood.hoon
gen/hood/overload.hoon
lib/hood/kiln.hoon

Makes |overload take a date so we can wipe the cache daily outside of business hours.
If merged you should be able to do something like, `|overload ~d1 ~2018.3.13..10.00.00`, where 10.00.00 is a middle of the night time for the west coast in UTC.
Part of mitigating #669.
Next up after this is to just have kiln do a poke to ford or eyre to cause a rebuild right after dropping the cache on the timer.

Fix |overload so it takes a date

---

lib/hood/kiln.hoon

While we are wiping the ford cache from |overload, we want to simulate an http request to prime as much of the ford cache as we can. Due to ongoing crashes in cttp, we try to fake it by replicating the ford %exec.
@belisarius222

Prime the cache during |overload

---

gen/hood/invite.hoon

Our |invite Hood generator for Womb invites currently caps at twenty
ship invites. This commit bumps that hard-coded cap to sixty-four, which
will allow me to send the appropriate number of star invites to our
[Winter 2018 contributor-award recipients](https://fora.urbit.org/posts/~2018.2.13..20.22.22..bddb~).

Add |invite support for up to sixty-four ships

---

sys/hoon.hoon

This forwardports #385, with a few additional changes:
- doccords (are these in the correct style? clear descriptions?)
- corrected typecast
- changed `++spin` argument order
The previously commented-out typecast reliably dumps core. Here's a representative backtrace: https://gist.github.com/joemfb/2884e2edf0e910beac630bef5b0c1ad0
I haven't been able to create a reproduction smaller than this:
```
|*  [a=(list) b=_|=(^ [** +<+]) c=*]
?<  ?=($-([_?<(?=($~ a) i.a) _c] [* _c]) b)
a
```
While that obviously shouldn't crash a ship (somehow not being virtualized?), I think fishing for a core like that is supposed to crash in the Hoon sense. I've switched to the common `=>  %=` typecast style.
As for the argument order, I think it's best for the gate to be last, particularly when it comes to …

fixes and documents ++spin/++spun (forwardport #385)

---

app/hall.hoon
app/talk.hoon
lib/hall.hoon
sur/hall.hoon

With this change, it becomes possible to specify a relative range in hall subscriptions to refer to the last x messages.
For example:  
`/circle/inbox/grams/-5` gets the last 5 messages from the inbox, and updates on all that follow.  
`/circle/inbox/grams/-5/-0` gets the last 5 messages from the inbox, nothing more.  
`/circle/inbox/grams/0/-5` gets all messages from the inbox, up to but not including the last five.
Subscriptions with a relative range start are always active, they will receive updates until their range end is reached.  
Subscriptions with a relative range end end immediately.
Tested this to update cleanly from the previous hall version, and to not cause connectivity issues when talking to out-of-date versions.  
Subscriptions to older ships that make use of this new …

Get last x messages from hall

---

sys/hoon.hoon

%tsfs, %tssm, %tshp, and, once #692 is merged, %tstr
closes #686
As this is just a minor change to the parser, it can be released live. Any feedback on where I should put `+espy` (a name I'm inordinately proud of, btw)?

generalizes =model syntax to be valid for any toro

---

app/hall.hoon
app/talk.hoon
lib/hall.hoon
sur/hall.hoon

The small change #658 made reached the structures used for communication between hall instances. Since it's not correct to assume all ships on the network get updates synchronously or at all, this is bad. To make this change, hall needs an interface versioning mechanism.
This comments out parts of the code from #658, for later re-enabling.  
I tried making `++prep` logic for this not awful, but that's actually kind of difficult.
Tested this to adapt state from current master fine. Restores the structures to their original state, so should make comms with outdates ships function again.
Re-opens #643.

Disable "last x messages" functionality in hall

---

app/hall.hoon
lib/hall.hoon

On getting the first federation payload (presences, configs and 100 most recent messages), the receiving Hall was generating diffs for these blindly, without checking if it already knew this data.  
When resubscribing federation (either manually or because a subscription needed to be rebuilt) this resulted in lots of traffic, because the diffs were sent off to all subscribers.  
With the changes in aaeb752, we check to see if received state is different from existing state, and only generate diffs if it is.
Also, for some reason, `%peer` diffs ("someone has connected to this circle") were sent out to parent nodes in federation. This data is only used internally in the "circle gets deleted, we need to end everyone's subscriptions" case.  
bc25403 makes sure these diffs don't get sent out. …

Hall: federation performance fixes & path parsing bug

---

sys/vane/clay.hoon

This fixes the symptom displayed in #681, but doesn't really address the underlying issue. This PR should probably be considered not ready to be merged until that has been resolved properly.
Currently, this PR only fixes the runtime error that would occur when trying to check revision zero for changes. It would try to look at the previous revision, but `(dec 0)` crashes. Now, it detects this and generates "file does not exist" results for all relevant files.
The underlying cause here is that the known latest revision for foreign ships (relevant [when converting a `%next` into a `%mult`](https://github.com/Fang-/arvo/blob/9f94497e87c28f8355c7a8628843b8f6bc02634e/sys/vane/clay.hoon#L1865) for code sharing purposes) is blindly used for `%next` requests, even when they're asking for changes …

Foreign ship %next requests

---

sys/hoon.hoon

(by converting the `tape`s in `+tank` to (list @c) before wrapping, then back)
This is a fix for unsafe unicode handling in general, and #674 specifically.
The "printable" structure `+tank`, designed for stack traces and type printing and slated for replacement, is heavily used in printing to the console. The renderer `+re` converts `+tank` to `+wall`, optionally wrapping long lines to a specified width. But since `+tank` consists of various combinations of `+tape`, which is a linked list of utf8 bytes, it's possible for `+re` to split multi-byte unicode codepoints, resulting in `%bad-text`.
For example:
```
> (~(win re [%leaf "abc’d"]) 0 5)
[%bad-text "[60 60 34 92 92 47 97 92 92 47 34 32 34 32 32 98 34 32 34 32 32 99 34 32 34 32 32 226 34 32 34 32 32 128 34 32 34 32 32 153 34 32 34 32 …
```

updates +win:re to wrap lines safely with regards to unicode

---

lib/hood/kiln.hoon
sys/vane/clay.hoon
sys/vane/eyre.hoon
sys/vane/ford.hoon
sys/zuse.hoon

This is #728 but tidier.
This PR changes the result returned for `%w` clay requests from `@ud` to `[ud=@ud da=@da]`, to aid in New Ford work.
Pretty sure I've found all existing usage of `%w` requests and updated them without doing anything weird.
As far as I'm concerned, this is ready for review.

Change %w care to return both @ud and @da cases

---

app/fora.hoon

In response to ~ravmel's issue here: https://github.com/urbit/fora/issues/6
With this change if you try to submit a post or comment without text, then the poke is ignored.  Yes, this is a really dumb fix, but it works and fora is minimalist anyway.  Only downside is there is no explicit feedback to the poster.  If someone wants to hold my hand a little I'll try to make a more fancy change.

Fora Posts and Comments with no text ignored

---

sys/hoon.hoon

This resolves an issue that I introduced when I refactor `+spin` and `+spun` in #649. The typecast of the sample gate `c` in `+spin` was throwing away the type of the head of the product, which is somewhat unfortunate:
```
> ? (spun "foo" |=([a=@tD b=@ud] [[b a] +(b)]))
it(*)
~[[0 102] [1 111] [2 111]]
```
With this fix in place:
```
> ? (spun "foo" |=([a=@tD b=@ud] [[b a] +(b)]))
it({@ud @tD})
~[[0 'f'] [1 'o'] [2 'o']]
```
My apologies for insufficiently testing the previous PR.

fixes +spin to preserve the type of the head of the product

---

sys/vane/ames.hoon

For the ~2018.5.24 continuity breach.

Bump Ames :protocol-version from 0 to 1

---

lib/hood/helm.hoon

This commit allows Ask app responsibility/load to get taken off of
~marzod and assigned to a dedicated Ask ship: currently, ~socden-malzod,
a child of Tlon's ops star, ~dopzod.

Transition ~marzod's Ask duties to a dedicated ship

---

sys/vane/ames.hoon

For the ~2018.6.8 continuity breach. See urbit/urbit#997.

Bump Ames :protocol-version from 1 to 2

---

sys/vane/clay.hoon
sys/zuse.hoon

Fixes https://github.com/urbit/arvo/issues/749
Since dict is only used once in clay, in the place that gets permissions for a scry, I changed its definition to:
```
++  dict  {src/path rul/real}
```
where real is
```
++  real  {mod/?($black $white) who/(set ship)}
```
And made the necessary changes in clay to handle this. 
Perhaps I should return all the group information rather than reducing it to a `(set ship)`. If anyone has any objections I can change it to `(set (each ship (map @ta crew)))`, or something else if you have a better suggestion.

clay permissions issue #749

---

app/dns.hoon
gen/dns/authority.hoon
lib/hood/drum.hoon
mar/dns/bind.hoon
mar/dns/bond.hoon
sec/com/googleapis.hoon
sur/dns.hoon
sys/vane/ames.hoon
sys/vane/eyre.hoon
sys/vane/gall.hoon
sys/zuse.hoon

This PR includes:
- new `%eyre` moves for the reverse reverse TCP proxy (`%wise` and `%that`)
- new `%eyre` moves for http(s) server config (`%form` and `%live`)
- new `%ames` moves for monitoring child-ship IP address changes (`%rove` and `%tend`)
- the dynamic DNS app and related components
These changes are all additive -- they do not necessarily require a breach. They are properly paired with an updated vere, however (I'll link those changes shortly). If run on a current-or-older vere, server configuration and reverse-proxy notification effects will simply be ignored.

adds dns app, http(s) server-config and proxy notification moves

---

sys/zuse.hoon

Based on the stack trace, I believe the lack of TCO in +ctra is the cause of #740. Thanks to @frodwith for the implementation!
I have successfully ticketed a star on a testnet ~zod with these changes, but I have not yet proven that it fixes an already-overflowing ~zod.

tail-call optimizes +ctra, +ctrb, and +ctrc in |aes

---

app/acme.hoon
app/dns.hoon
lib/hood/drum.hoon
lib/oauth1.hoon
lib/oauth2.hoon
mar/acme/order.hoon
mar/recoverable-error.hoon
sur/dns.hoon
sys/vane/eyre.hoon
sys/zuse.hoon

This PR adds the new LetsEncrypt client app `:acme`, and builds on the `:dns` app and `%eyre` changes in #752.

adds letsencrypt client :acme, integrates with :dns app and %eyre

---

sys/hoon.hoon

(I messed up a previous version of the PR, so I closed that and am trying again with this one.)
@rmariani ran into an endless loop when he tried passing `0` to `rad:og`: https://github.com/urbit/urbit/issues/1016#ref-pullrequest-342508381
This edit causes `rad:og` to crash with a `rad-zero` when the sample is `0`.

crash `++ rad` when arg of `0` is used

---

sys/hoon.hoon

`+mz:nl` was determined by ~sorreg to be dead code, and there doesn't seem to be any possible `a` that will nest in it.
Also, `+bif:in` and `+bif:by` had the weird syntactical construct of `=<  [+< +>]`. I simplified it to the more straightforward `=< +`.

removes dead +mz:nl, updates +bif syntax

---

lib/test/ford.hoon
tests/sys/vane/clay.hoon

Wrote an `+expect-schematic` function in /lib/test/ford/hoon and used it to simplify the Clay tests.

+expect-schematic in ford test lib

---

sys/vane/jael.hoon
sys/zuse.hoon

This PR contains two sets of changes.
First, it updates the zuse-constitution and jael logic to work more cleanly with the current version of the contracts. Aside from a few tweaks, I did a quick look-over of the existing logic, and it all still seems to match the contracts.
Secondly, it makes jael track continuity... sort of. When a ship indicates a continuity breach on-chain (or we've just never met it before), its `live` aka continuity flag will get set to `|`. It is then up to @joemfb's modified ames to send a `%meet` task to jael when we finally manage to connect with that ship again, setting the flag to `&`.  
Changes to this flag get sent as part of the existing `%pubs` subscription, which has been updated to always send full public key state for a ship (now `[live=? life=life …

Constitution + jael updates

---

lib/test/runner.hoon

This runs and displays tests in alphabetical order instead of in whatever ordering there was in the map.

Run tests in alphabetical order.

---

sys/vane/ford.hoon
tests/sys/vane/ford.hoon

Ford should now rebuild live builds when /sys/hoon/hoon, /sys/arvo/hoon, or /sys/zuse/hoon change.
Hopefully fixes https://github.com/urbit/arvo/issues/796.

fix ford %reef dependency tracking

---

sys/vane/ford.hoon
tests/sys/vane/ford.hoon

Now when Ford builds the standard library, it compiles Zuse against the `..is` core from Arvo. This is how Arvo itself builds Zuse. Up until now, we had been compiling Zuse against the whole Arvo core, which took longer to cause errors than I would have expected, but it did eventually cause some. This patch should fix those.
I left the `+disabled-test-reef-slow` unit test disabled for CI because it lives up to its name, but I verified it does pass.
@joemfb you probably want to see this too, since you found the bug with us.

Fix %reef handling more. Now uses the right part of the arvo core

---

sys/vane/eyre.hoon

`%core` schematics now require a real path, instead of assuming a `hoon` suffix.

Be explicit in having hoon file suffixes in security driver paths.

---

app/dojo.hoon

Make dojo not produce incorrect beams when they start with '/'.

---

lib/test/ford.hoon
tests/sys/vane/clay.hoon

The first clay test now validates the entire sequence of initializing Clay and writing two files.
Also refactored `+expect-schematic` so it just takes two schematics, instead of a schematic and a vase.

refactored +expect-schematic and completed first clay test

---

sys/vane/clay.hoon
tests/sys/vane/clay.hoon

All but the first write request during an Arvo event gets enqueued, to be run in a later event triggered by a Behn timer. There's a test on this behavior, which passes.
This doesn't entirely fix referential transparency for date-base read requests, but it should at least make it less likely for referential transparency to be violated. Fixing this problem in its entirety is actually a bit tricky, and we will need to think it through in more detail. This is just a quick patch.
The failing case is that someone does a read request at the current date, then does a write request in the same Arvo event, then performs the same read request a second time, which now has a different answer.
I still think it's worth adding this to see if we can unblock the collections integration, even if it doesn't …

Enqueue second Clay write during an Arvo event

---

sys/vane/eyre.hoon

Elliot's oauth2 bug fix for eyre, cherry-picked from the testnet-rc branch

Fix path to oauth atoms.

---

sys/vane/ford.hoon
tests/sys/vane/ford.hoon

This fixes a bug in +make-join where following the +grad arm will cause a build to add itself as a dependency. This adds a test to ensure this doesn't regress.
This also adds several assertion that ensure that a client is not in the list of its sub builds, which were useful in tracking down this bug.
review: @belisarius222 
cc: @ixv

Fix +grad case in +make-join

---

sys/vane/ford.hoon

This should fix the bug encountered by @ixv on the testnet where Ford crashed due to a missing sub-build during `+copy-build-tree-as-provisional`.
The bug was triggered by `+move-root-to-cache` performing a double mutation of a sub-build in the case of a triangle build, where build A depends on B and C, and build B also depends on build C. The fix was to add a check to no-op if we'd already mutated that sub-build.
This PR also contains a minor optimization that removes some vestigial code from `+remove-single-build`, in addition to a cosmetic cleanup in `+add-client-to-sub`.
Closes https://github.com/urbit/arvo/issues/819.

fix bug in +move-root-to-cache

---

sys/vane/ford.hoon

lack of tail-call optimization in one of the functions was blowing the stack, causing issue: https://github.com/urbit/arvo/issues/826
removing the !: at the top of the file fixed this.

removed zapcol from ford

---

sys/vane/clay.hoon

My previous PR (https://github.com/urbit/arvo/pull/839) could crash on some inputs that weren't of mark `%mime`. This PR fixes that, and it adds an optimization: if Clay receives a new version of a file (a `%mut` `+miso`), first check noun equality of its contents against the current contents for that path; if they're the same noun, don't produce a Ford build for that path.

fix clay cache for non-%mime entries; also add equality check as optimization

---

sys/zuse.hoon
tests/sys/zuse/dawn.hoon

This PR adds the `|dawn` core, to be used by vere to generate requests, parse responses, and validate what will become the boot event.
I've opened this PR now because I've already fought some regressions and incompatibilities, and would like this test-suite to be enabled going forward. More to come soon.

adds pre-boot validation

---

app/dojo.hoon

Reinstates the `+he-lens` arm that responds to Unix IPC commands passed in from Eyre. Modifies the `+hoon`s produced in the arm since `+hoon` changed in the release-candidate branch.
I have not tested the lens functionality, but Dojo compiles and runs.

dojo: reinstate +he-lens with fixed +hoon

---

app/dojo.hoon

Added ++poke-lens-command back into dojo.hoon with a similar fix to the addition of ++he-lens

reinstated ++poke-lens-command with changes

---

sys/zuse.hoon

I've been playing around trying to glue urbit and IPFS together. For my first iteration, I tried to `+curl` my local IPFS API from the Dojo. Because `go-ipfs` [doesn't implement HTTPS](https://github.com/ipfs/faq/issues/136#issuecomment-227264141), I made sure to do a `+curl "http://localhost:5001..."`, but I was still getting an ssl related error:
```
> +curl "http://localhost:5001/api/v0/get?arg=QmagqTLSZvdqjWp2hVFokDyThekNAACsUG8r2XGhBWPQh6"
< http://localhost:5001/api/v0/get?arg=QmagqTLSZvdqjWp2hVFokDyThekNAACsUG8r2XGhBWPQh6
http: fail (170, 504): ssl handshake failure
HTTP 504
```
Talking to @Fang- at the last meetup, he reassured me this should not be happening, and specifying "http" should do a regular non-ssl request. I dug in a bit and found the issue: in the definition for `++ …

Remove forced ssl upgrade for localhost http requests

---

sys/vane/jael.hoon
sys/zuse.hoon

I hardcoded the block number of the initial deployment, and now it chunks every 5760 blocks (~1 day) from that point.  This should reduce the frequency of timeout problems quite a lot.
I've also got the beginnings of a snapshot system there (it takes the snapshots, but there's no way to restore them yet).

add chunking and start snapshotting

---

sys/vane/jael.hoon
sys/zuse.hoon

This adds rewinding in the case where our node tells us that a log got reorg-ed out of the chain, as suggested by @Fang-.
Arguably, we should also rewind when a filter times out or when we switch nodes.  I've opted against that for now and noted the reasons for that decision in the source.  It's a little unusual to put those arguments in the source, but if we stumble over a reorg and someone's debugging it, I want them to see the potential pitfalls of how it works now.
I believe this puts a bow on my snapshotting work, so any final comments or suggestions are welcome.

Rewind automatically when we detect an Ethereum reorganization

---

sys/vane/eyre.hoon
sys/zuse.hoon

Sometime this summer (fall?), %eyre stopped successfully parsing oauth2 redirect urls from google.
An example with the printf added in this pr:
[ %eyre-parse-url-failed
\/'/~/ac/googleapis.com/_state/in?state=_&code=4/ZZZZZZZZFyuRFw3mZZZZZZZZZ8Z\/
ZZZZZZZZCym_B9DFiOlwPTMvZZZZZZZZpzLLqk1MvcBiNQZZZZZZZZIwFg3o&scope=openid%
20email%20https://mail.google.com%20https://www.googleapis.com/auth/plus.m
e%20https://www.googleapis.com/auth/userinfo.email%20https://www.googleapi
s.com/auth/ndev.clouddns.readwrite%20https://www.googleapis.com/auth/cloud
-platform.read-only'
\/                                                                          \/
]
The culprit is the colon(s) in the scope parameter. There seems to be some disagreement about whether it needs to be escaped in url query-parameters. …

fix eyre path parsing for security drivers

---

sys/hoon.hoon

In Udon, you can now display a literal ``` in code-quotes using this syntax:
```
`\``
```
big thanks to Ted for helping me with this.

Fixes ``` Udon parser bug

---

app/acme.hoon
lib/jose.hoon
lib/pkcs.hoon
tests/app/acme.hoon
tests/lib/jose.hoon
tests/lib/pkcs.hoon

This PR implements more robust request retries on timeouts and other recognizable failure conditions.
Due to testnet woes, this has not yet been fully tested. Opening now for review, additional fixes will be pushed here as necessary. Rate-limit handlers should also be implemented here.

adds robustness to :acme app

---

sys/hoon.hoon
tests/sys/hoon/auras.hoon

It's `@p`, except never scrambles, doesn't care about even number of bytes, and doesn't use `--` in large values.  
This is needed for tickets, and useful for anything else that may want to use the `@p` look-and-feel to display data.
Syntax for literals is `.~`. A `.~` by itself is invalid, you need at least one syllable. They follow byte ordering as in the `@ux` case, so:
```hoon
@ux       @q
0x1       .~nec
0x201     .~binnec
0x3.0201  .~wes-binnec
```
Note that leading zeroes are valid, but won't change the value. `.~dozzod-dozzod` is equivalent to `.~zod`.
I have included some tests! Pretty sure this is how you test auras: just using them.

Add @q, phonetic data representation

---

lib/keygen.hoon
tests/lib/keygen.hoon

For details on these changes, see urbit/fora-posts#9.
The tests here mimic what's done in keygen-js, but the "doesn't equal" case looks a little bit silly because `/lib/test` doesn't offer a non-equivalence check yet.
Also taking this chance to update the tests to use actual `@q` notation, now that that's in.

Update /lib/keygen to match latest spec

---

.travis/get-or-build-pill.sh
.travis/pin-parent-pill-pier.url
gen/brass.hoon
gen/ivory.hoon
gen/solid.hoon
sys/arvo.hoon
sys/vane/ames.hoon
sys/vane/behn.hoon
sys/vane/clay.hoon
sys/vane/ford.hoon
sys/vane/gall.hoon
sys/zuse.hoon
tests/sys/vane/ford.hoon

The PR restores the formal Arvo interface gate (equivalent to `+poke`, and expected by cc-release), and updates `+solid` and `|reset` to with/around that interface. It also improves error handling in arvo and some vanes (fixing issues that come up when booting cc-release). And it adds `%zuse` to the `+ivory` pill, and all of (current) userspace to the `+brass` pill.
I have a branch of vere that merges `cc-release` and `release-candidate`, and can boot fake galaxies off of it. I think that's as far as we can get in a dual-boot scenario, without significantly complicating vane initialization or the boot sequence. I have some more cleanup and work to do on that merged branch, than I'll push it. Since the changes in this PR are necessary and compatible, I'm opening it early to avoid potential …

dual boot with cc-release

---

sys/arvo.hoon
sys/vane/ames.hoon
sys/vane/behn.hoon
sys/vane/clay.hoon
sys/vane/dill.hoon
sys/vane/eyre.hoon
sys/vane/ford.hoon
sys/vane/gall.hoon
sys/vane/jael.hoon

#896 revealed an issue with the way the kernel does caching. The previous design had one single compiler cache shared across all vanes. This compiler cache was never cleared. This meant that old results from +mint could be used after types had changed, as they were globally cached.
This moves the cache from a per-arvo to a per-vane basis, and properly clears the cache on vane reload.

Arvo +worm cache per vane

---

sys/arvo.hoon

So. This trace is illuminating about why Ames is slow.
The majority of the time in Ames is spent either parsing things (`+nuck:so`) or inside the compiler before/after the scry to Jael.
This fixes the scry part, so that scry's don't invoke the compiler. The majority of time in handling a scry is spent in the compiler since it doesn't use the compiler cache since scrying can't have side-effects and modify the cache. So prime the worm cache at vane install time so the cache is prepopulated before we call a scry.
I'm not sure if this is the best way to structure this patch, so please read it critically, but this does shave >10ms per Ames call which scrys into Jael. That said, I think I've tested every case of `|reset`/`+solid`/vane load, and have confirmed with printfs that the compiler …

Prime the worm cache in arvo with scry types

---

sys/vane/behn.hoon
sys/zuse.hoon

As discussed in #906, every vane that accepts tasks from unix must be able to handle a `%curd` task. `%behn` was the last that did not. (And this is not an abstract change -- it came up as an issue when I was merging cc-release)

handles %crud in %behn

---

sys/hoon.hoon

+slay is a giant, recursive, slow parser combinator. +slaw is called
on every beam handling, on Gall +take, etc. In actual usage, we can
special case based on the passed in type and use a much smaller
parser.

Do fast special cases for +slaw instead of always calling +slay.

---

sys/hoon.hoon

Also fast path %uv so that vere can directly call +slaw instead of +slay. The HTTP wires use `0v` values as identities and vere currently calls `+nock:so` raw to handle this. We can fast path this though.

Also add %uv handling to +slaw

---

sys/hoon.hoon

+slav calls +slaw with %da and %ta in several places across multiple
vanes. This refactors the date parsing code into its own arm so it
can be called from +slaw.

Add special cases for %da and %ta to +slaw

---

sys/arvo.hoon

There is some weird failure in the +wa cache code that happens when hoon.hoon gets changed. I can't repro this on demand, so I want to add a bunch of ~| to debug.

Add ~| to arvo to try to debug intermittent crash.

---

sys/hoon.hoon

While jetting +sort (urbit/urbit#1088), I made it do only a single
pass to separate the list around a pivot instead of using two. Do
this in the hoon code, too.

Don't do two passes in the unjetted +sort

---

sys/arvo.hoon

When we activate a vane, we should pass in real entropy instead of just hashing `now`. When we modify entropy, we should hash the concatenation of the old entropy and the new entropy instead of just xoring them.

Move from just hashing time to using actual entropy.

---

sys/hoon.hoon

+turn now no longer has a TMI problem, nor does it lose its product type, even if passed a wet gate to transform the list.
The product type had to be calculated by type-inferring the product of running the input gate on an element of the list. Otherwise, a wet input gate will cause +turn to lose specificity in its output type, since the type of each element in the product list would be the result of inferring the input gate across its default sample.

Fix turn types

---

sys/arvo.hoon
sys/hoon.hoon
sys/vane/ames.hoon

+sloy is practically how we perform most scrying. It parses wires
using the full +slay when several of the elements. Replaces all
usages we can with +slaw.
The long term fix is to move to not parsing wires, but that won't
happen before current release-candidate is released.

Dont nuck in sloy

---

.travis/pin-parent-pill-pier.url
gen/brass.hoon
gen/metal.hoon
gen/solid.hoon
sys/arvo.hoon
sys/hoon.hoon

Added a `+slum` gate to encapsulate calling a gate using Nock. Also removed cases where we were using `.*(gat -.gat)` where we should have been doing `.*(gat [%9 2 %0 1])` so we don't lose jetting.

+slum to call raw nock gate; some associated cleanup

---

sys/arvo.hoon
sys/vane/ames.hoon
sys/vane/dill.hoon

Right now, in Ames and Dill, we are rendering to `@tas` all the path components in scry paths. This overhead is clearly visible in a runtime flame graph. Introduce a version of +sloy which takes its arguments instead of parsing its arguments out of a path.
The correct long term fix to fix this entire class of issue is #926, but this hack is enough to speed up each ames packet by a few milliseconds.

Light version of +sloy

---

.travis/pin-parent-pill-pier.url
gen/solid.hoon

Minor follow-up to https://github.com/urbit/arvo/pull/923 that uses the new +slum gate in the gen/solid generator.

use +slum in gen/solid

---

app/ask.hoon
app/dojo.hoon
app/hall.hoon
app/talk.hoon
lib/hall.hoon
lib/hood/drum.hoon
lib/pill.hoon
lib/sole.hoon
sur/asn1.hoon
sur/hall.hoon
sur/lens.hoon
sur/plan/diff.hoon
sur/sole.hoon

This removes some redundant libraries, replaces some `=,` with explicit references, locks some libraries and structures with `^?` and removes some `^`.

Remove some tiscom

---

sys/vane/ames.hoon
sys/zuse.hoon

This pattern required a special-case in the event/effect processing. That pattern was synchronous, so handling it in the runtime offered no advantages -- instead we just recur here.

removes strange %ames self-gift when forwarding to self

---

sys/vane/ford.hoon

This speeds up the +gather step in Ford. By not doing a full scan and a sort every
time we add a build, we remove ~30ms of latency from each chat message
sent my landscape.

Speed up +put:by-schematic

---

sys/vane/ford.hoon

+sell invokes the type checker and thus adds 10ms to each event
where it is used. +sell is invoked in "tapes like {<this>}". Ford
error messages use that format on errors. Many common Ford builds
are expected to fail, but swallow the error messages. This modifies
them so that they generate their error messages in a cheaper way.

Don't call +sell in normal cases in Ford.

---

sys/vane/behn.hoon

Clay expected responses to its timers to come back in the same order it sent them. So needy!
Now Behn actually does this.

Fix Behn bug that broke Clay

---

app/dojo.hoon
app/hall.hoon
app/test.hoon
lib/collections.hoon
lib/hood/kiln.hoon
lib/hood/write.hoon
sys/vane/ames.hoon
sys/vane/clay.hoon
sys/vane/dill.hoon
sys/vane/eyre.hoon
sys/vane/ford.hoon
sys/vane/gall.hoon
sys/vane/jael.hoon
sys/zuse.hoon
tests/sys/vane/ames.hoon
tests/sys/vane/clay.hoon
tests/sys/vane/ford.hoon
tests/sys/vane/jael.hoon

The Costello to #915's Abbott. This removes all the multi-homing indirection in the state, state-machines, and moves of all the vanes. The closes thing to an exception is `%gall`'s `%deal` task, which takes a pair of ships, but uses them alternatively for bidirectional communication.
I've tested networking, syncing/merging, and cross-ship app pokes in a number of scenarios, but there's obviously still risk involved in making this many changes across this many places. Drive-by reviews of the area one knows best would be greatly appreciated.

single-home the vanes

---

sys/vane/ford.hoon
sys/vane/jael.hoon

I think it was already in %jael, but I mistakenly added `!:` to %ford in #941.

removes !: from vanes

---

lib/hood/kiln.hoon
sys/vane/clay.hoon

by using `%that` instead of %init for sync merges into desks at cases 1-3. This fixes broken planet clay syncs on boot, a bug which was introduced with the new pill format in #909.
The error messages in `+apply-foreign-update` were broken, this also fixes them and refactors the function.

fixes %clay sync merges for planets

---

sys/vane/ames.hoon
sys/vane/jael.hoon

by scrying into `%jael` for public keys when meeting new ships. Also cleans up `%ames` packet acceptance.

drop fewer packets

---

sys/arvo.hoon

Behn is sensitive to the order in which ova are emitted, which was not
correct. Previously, ova emitted first within a single vane activation
were processed as effects last.

Fix arvo ova order

---

sys/vane/eyre.hoon

Eyre used to reach an inconsistent state if it received the %born event on Vere restart. This PR makes sure we properly unqueue each request from the security driver that emitted it, if there was one.
This work was done with @joemfb

Eyre clean up outgoing requests on restart

---

sys/vane/clay.hoon
sys/vane/eyre.hoon
sys/vane/gall.hoon
sys/zuse.hoon

%ames no longer sends %went, but %clay, %gall, and %eyre still had (stubbed out) handlers for it. Closes #47.

removes the last of old %ames ack move %went

---

sys/zuse.hoon

Event signatures hadn't changed, but some arguments had become indexed. This affects event parsing.

Update Azimuth event handling to account for updated indexing

---

sys/vane/dill.hoon
sys/vane/jael.hoon
sys/zuse.hoon
tests/sys/vane/jael.hoon
tests/sys/zuse/dawn.hoon

That is, sponsorship is no longer `(unit ship)`, but rather `[? ship]`, so that we retain knowledge of a ship's most recent sponsor even after it is kicked.
This allows us to do the simple-dumb solution to "what if no sponsor" by just relying on the "current/last known" sponsor always. In the case the ship itself isn't active or known, jael's `++sein` still falls back to the prefix.
Open question here is what sponsor to provide for comets. I've hardcoded ~marzod for now, but this should probably pull from the "comet stars" list. iirc that's the approach we settled on?
This doesn't *seem* to require any `dawn.c` changes, aside from some comments. @joemfb please confirm.
I tried booting a ~marzod off the Ropsten deploy, but couldn't get it to reach the ~zod, probably because of existing …

Treat sponsorship like it's treated on-chain

---

sys/hoon.hoon

This PR extracts the type-safety change to `+uno:by` from #785.

adds explicit types to the sample of +uno:by

---

sys/vane/ames.hoon
sys/zuse.hoon

This field is obsolete, the +life is passed in the outer packet wrapper and validated therein. It's presence was preventing the sending of negative acks.

removes +life from %bond +meal (to fix nacks)

---

sys/vane/ames.hoon

This fixes two issues that were leading to more than necessary %open-outgoing and dropped-incoming packets. In one case, we weren't scrying for a +deed where we could be, in the other, we were scrying, but always guessing a +life of 1. This PR also renames the %jael scry gates for clarity.

scry for +life in %ames (fewer %open packets)

---

sys/vane/ford.hoon

Note that this doesn't apply to the `/~` rune, which parses its input into Hoon more greedily. For all other Ford runes, though, this should parse late-bound paths using :path-to-render instead of the path of the renderer file itself.
@vvisigoth you might want to test this before merging; this compiles, but I didn't have a renderer at hand to throw at it.
@eglaysher I'd appreciate a quick sanity check from you, since you wrote most of this part of Ford.

% means path-to-render in renderers

---

sys/vane/clay.hoon
sys/vane/ford.hoon

When getting mark definitions to compare a foreign commit against its merge base, we need to use `case-to-aeon` of the foreign desk, not our local one.
I've tested that this fixes the issue locally, but I haven't tested it with multiple ships.

use foreign aeon for foreign mark definitions

---

sys/vane/eyre.hoon

This PR suppresses a couple printfs that were always being triggered on authentication redirects.
/cc @ixv

remove %eyre auth redirect printfs

---

mar/urb.hoon

I found an issue where `"` would render as `â€` in markdown. I asked @ixv for help and he fixed it so it has the utf-8 charset. Interesting, `master` does not have this problem.

Adds utf-8 rendering

---

app/eth-manage.hoon

We need to be able to kick jael if it stops listening to the ethereum node.  This app does that with `:eth %look`.
This should probably be cleaned up, but it's vital functionality for now.

add eth-manage app

---

mar/snap.hoon
sys/vane/gall.hoon
sys/vane/jael.hoon
sys/zuse.hoon

`.^([latest-block=@ud source=(each ship node-src:jael) %j /=eth-status=)` now gives you some useful information about your current jael state.
I also added a `snap` mark so we can load these snaps into clay and inspect them.
Finally, I added a `%snap` option to `%jael` and `%eth-manage` so that we can restore a snapshot that we put in clay on-demand.

Quality-of-life improvements for %jael

---

sys/vane/clay.hoon

fixes #1008 
I'm not sure this is the right solution, but if we run into issues with clay being rickety, this is a solid hotfix that makes sense to me, at least while we're regularly breaching (so we can expect peoples' hoon/zuse/arvo/marks to be pretty compatible).
I suspect we'll eventually want to revert this and instead compile the foreign marks with the foreign kernel, but it has to be done at the new revision, and I don't know how to tell ford about the new kernel for that desk before the revision is even complete.

always use our reef for clay

---

app/acme.hoon

This was anticipated to work with the generic `:acme` retry mechanism through `&recoverable-error`, but the trigger for that code path is failed mark conversions.
This PR adds explicit handling for `HTTP 429` responses, and matches on the two rate-limits we're likely to hit, falling back to more generic retry with exponential backoff if it can't match them. Additionally, it updates the certificate renewal timer logic to be biased towards the end of the week (see comment).

adds rate-limit handling to :acme

---

sys/arvo.hoon

@eglaysher's recent profile shows a significant percentage of Ames processing time inside Arvo's +scry function, almost all of which happens on +slym:wa cache misses. Since we don't actually use the type from the result of the +slym call, there's no reason to call the compiler. Just run the function untyped using +slum and clam the output to `(unit (unit (cask)))`.

slum in Arvo scry

---

app/hall.hoon
sys/hoon.hoon
sys/zuse.hoon

`+has:in` now ensures type safety on the element. It ain't pretty, but it works. Also keep in mind that this function is jetted, so its internal mischief won't cause performance issues.
cc @eglaysher

+has:in typecheck hack

---

sys/vane/ames.hoon
sys/vane/behn.hoon
sys/vane/clay.hoon
sys/vane/dill.hoon
sys/vane/eyre.hoon
sys/vane/ford.hoon
sys/vane/gall.hoon
sys/vane/jael.hoon
sys/zuse.hoon

Dill wasn't asking, and Jael didn't know how to answer. Now Jael's memory is reported in a format like this:
```
%jael:
%yen: B/0
%urb: B/264
%sub: B/744
%etn: B/0
%sap: B/48
--KB/1.056
```
If we want more detail, we could probably take the list of snapshots in `sap` and print out their sizes one by one, turning their event number into a `@tas` to identify them. Seemed like overkill for now, though.

Handle |mass in Jael

---

app/eth-manage.hoon

Adds %look-kick functionality to the eth-manage app, which allows you to change what source you are downloading snapshots from.
Changing this source seems to fix the problem of stars getting stuck on an old block number.

added look-kick functionality to eth-node

---

.travis/test.js
sys/vane/dill.hoon

This resets `hef.all` before printing |mass, so that other vanes' memory reports don't get absorbed into Dill's.

fix self memory printing in dill |mass

---

sys/vane/eyre.hoon

Inside +execute-turbo in eyre, we moved the tank outside of the |. so that it's not held as a thunk. This stops ford from holding onto an 80MB error message in one of its caches.

build tank outside of |.

---

mar/json/rpc/response.hoon
sur/json/rpc.hoon
sys/zuse.hoon

This adds a type for json-rpc requests, and provides a few utility functions for turning it into more directly useful things (`json`, `hiss:eyre`).
Also removes a `/sur/json/rpc` that was still there, even though the json-rpc structures have lived in zuse for a while already.
Yes, the latter `++jrpc` shadows the former. This seems like a more elegant solution than separating types across cores, as we do for some `++ethereum`  and `++azimuth` things.
"This belongs in a lib!" json-rpc support is already in zuse though, and needs to be because jael and dawn depend on it. Having it only partially in the stdlib feels even weirder. Happy to discuss this though.

Provide better json-rpc request affordances

---

sys/hoon.hoon

ensures  defaults in $~ specs nest in the actual structure

---

lib/hood/helm.hoon
sys/arvo.hoon
sys/vane/ames.hoon
sys/vane/behn.hoon
sys/vane/clay.hoon
sys/vane/dill.hoon
sys/vane/eyre.hoon
sys/vane/ford.hoon
sys/vane/gall.hoon
sys/vane/jael.hoon
sys/zuse.hoon

This PR updates arvo to send a `[%vega ~]` task to every vane after a kernel upgrade (and after the %zuse and the vanes have been recompiled as well).
Right now, the task handlers in each vane are just stubs. I think the most pressing feature is to make %ford clear it's cache and rebuild all live builds. This PR could go in as is, or it could be held open until the task handlers themselves are also implemented.
Note that this change creates an awkward naming collision in %dill, which already handles a %vega task (to trigger the kernel upgrade). I've handled this for now with an ugly type fork. Eventually, the different moves that together make up the kernel upgrade procedure should probably have different names.

notify vanes of kernel upgrades

---

sys/arvo.hoon
sys/vane/ames.hoon

%ames keeps a `+crub` core with its keys already installed. I don't know if this was a performance optimization, or just an artifact of an earlier time. In any case, we now re-establish that core after a kernel reset.

adds some details to |mass, plug a leak in %ames

---

.travis/test.js
lib/hood/drum.hoon

Currently, when you launch a new ship, after initialization, you are dumped into talk. This change makes it so you are dumped into dojo instead.
The thing you are dumped into is a consequence of sort order over the `ray` set defined in `lib/hood/drum.hoon`. Under the previous `mug` algorithm, it happened that `dojo` was first.
This fixes issue #1033.

Make a new ship launch into dojo

---

sys/vane/behn.hoon

While debugging issues in aquarium, I changed these behaviors of behn.  With these changes, I think it's now true that we fire no more than one timer in an event, and only if this is a %wake event straight from unix.  This should make it much easier to reason about behn's behavior.
There was never any good reason to fire a timer while setting another timer, right?  I think I was running into a situation where I'd have one thing set a timer for `now` to try to wait for the next event, and then another would do the same thing in the same event, which would fire the first in the same event.
It's super weird, btw, that we `(flop moves)` in several places rather than once in a `++abet`-style function.  I *think* the flops are right, but I really can't tell.

Don't fire timer in the middle of another event and take one timer at a time

---

sys/vane/jael.hoon
sys/zuse.hoon

[Relevant Ethereum JSON RPC docs section.](https://github.com/ethereum/wiki/wiki/JSON-RPC#a-note-on-specifying-topic-filters)
Rather than a flat list of topics to watch for, it is an indexed/ordered list of topics to watch for in those specific positions. As such, items in that list may either be:
- zero (null, matches any topic in that position)
- non-zero (matches one specific topic in that position)
- a list of topics (matches any one of those topics in that position)
Additionally, topics are always specified using 32 bytes, so there is no need to specify length explicitly.

More accurately represent Ethereum RPC filter topics

---

sys/zuse.hoon

Does what it says on the can. This is useful for dealing with external services that give you dates in the form of Unix timestamps.

Implement +from-unix for turning Unix timestamps into @da

---

sys/zuse.hoon

Because `+cat` doesn't care to left-shift if you append a zero value.
Previously:
```hoon
> (decode-topics:rpc:ethereum ~[0x0 0x1] ~[%uint %uint])
[0 1]
> (decode-topics:rpc:ethereum ~[0x1 0x0] ~[%uint %uint])
[0 1]
```
Now:
```hoon
> (decode-topics:rpc:ethereum ~[0x0 0x1] ~[%uint %uint])
[0 1]
> (decode-topics:rpc:ethereum ~[0x1 0x0] ~[%uint %uint])
[1 0]
```

Fix topics decoding to work with zero values

---

sys/hoon.hoon
tests/sys/hoon/auras.hoon
tests/sys/hoon/ob.hoon

(Resolves #1105)
`+ob`, a core that implemented a permutation cipher for planet-sized atoms, contained a critical bug that allowed multiple inputs to encipher to the same output.  This created collisions between some planet-sized `@p` values.
The rewritten version corrects the bug, and also rewrites `+ob` to more clearly match both 1) the paper that the algorithm comes from, and 2) the parallel implementation in urbit-ob that has gone through a full-scale exhaustive test.
The rewritten version is also itself easier to test; this PR adds a small-scale exhaustive test, as well as small battery of sanity checks on `+ob` internals (including on `@p` values previously known to collide).
NOTE: One thing I'm observing here is that dojo may be lagging behind on changes to hoon.hoon.  For example, …

+ob overhaul

---

app/talk.hoon

In a multi-target situation: if there is a bound glyph for a target, instead of showing both the glyph and the target, show just the glyph.
So, if I have `+` bound to `~dopzod/urbit-help`, `&` bound to `~paldev/music`, and set my audience with `;+,&`, then currently you'll see:
```
~palfun-foslup:talk[+ ~dopzod/urbit-help & ~paldev/music]
```
But after this PR, you'll see:
```
~palfun-foslup:talk[+ &]
```

Print selected talk audience more compactly

---

sys/vane/rver.hoon
tests/sys/vane/rver.hoon

Logan mentioned that we weren't returning 403 on authentication failures for the channel.js stuff.

Centralize error pages in one gate and support 403 on unauthenticated.

---

README.md
mar/md.hoon

Comes with usage instructions largely copied from `urbit/urbit`, minimum viable developer instructions, minimum viable contributor direction, and minimum viable flair.
Happy to take suggestions for better copy right now, or punt on that and merge as is. This will definitely need a rewrite at some point.
Also, how do we want to deal with Arvo's lack of `.md` support? We'll want a readme **`.md`** for Github presentation reasons, right?

Add a readme

---

mar/md.hoon

The md mark didn't have a `+grad`, so it crashed if you ever changed an md file.
It also lacked a trailing newline.

add +grad to md mark

---

sys/vane/behn.hoon

Various vanes set timers during the boot sequence, and `%behn` immediately gives `%doze` effects as appropriate. This combination was requiring that the `%born` event (new process notification) be injected as early as possible, and generally made %behn inflexible during boot.
I can't think of any reason why it might be harmful to defer the `%doze` effect -- any pending timers will be picked up and processed as soon as the `%born` event is injected.

updates %behn to no-op if its unix-duct is unset

---

sys/vane/ford.hoon

Took me a minute to realize this was the `%md` mark:
```
ford: %cast mdon [~zod home] failed
```

corrects %ford %cast error messages

---

app/aqua-behn.hoon
sys/vane/ames.hoon
sys/vane/behn.hoon
sys/vane/clay.hoon
sys/vane/eyre.hoon
sys/vane/jael.hoon
sys/zuse.hoon

This sets the groundwork for future work for vanes to handle async errors. I just added stubs to the various vanes for now, but at least they now have the error information.
A `|reset` passed, but I have not done more detailed testing on this. Not sure if there's a convenient way to test. Maybe pH?

Behn pass errors to client vanes

---

sys/vane/clay.hoon

The core at +7 is not registered, so this hint was causing failed-registration printfs in the dashboard.

fixes +rift-scry jet registration hint in %clay

---

.travis/pin-parent-pill-pier.url
.travis/test.js
sys/vane/ames.hoon
sys/vane/jael.hoon

As discussed briefly in urbit/urbit#1236, %ames initialization is particularly fragile, and requires special accommodation by the runtime. This PR makes the handling of the ames process/boot event `%barn` more robust, at the expense of dropping (and therefore subsequently retrying) packets sent during the boot sequence.

hardens %ames initialization

---

lib/ph.hoon
sys/vane/clay.hoon

This is not a pressing issue -- consider it a UX feature request.
I've long found these printfs to be superfluous, but it's gotten much worse (imo) with the growth of userspace. This is really highlighted when you boot ships in :aqua.
The printfs are replaced with
```
clay: committed initial filesystem (hoon)
```
for `base/1`,  and
```
clay: committed initial filesystem (all)
```
for `base/2`

suppresses %clay file-change printfs for initial filesystem

---

sys/vane/clay.hoon

The new clay "initial filesystem" printfs introduced in #1139 were spuriously being triggered by any external syncs to any desk other than `%base`, if `%base` was mounted (because all mount-points are synced). This is fixed by checking that there are actual changes being made before printing.
Also removes some debug printfs in `+load`.

fixes clay boot printfs

---

sys/hoon.hoon

Refer to #1145 for a discussion of motivation and some alternatives.
This introduces a new synthetic rune `=%`.  This:
```
=%  a=@  b  c
d
```
Expands to this:
```
%+  (b a=@)
c
|=  a=@
d
```
The intended use case is monadic operations.  Here's an idiomatic real-world example where I use it to boot two ships and have them `|hi` each other.  Note that each of these actions requires sending moves to another gall app and receiving multiple responses from that app.
```
=/  m  (ph ,~)
^-  data:m
=%  [%booted from=@p]     bind:m  (boot-ship ~bud ~)
=%  [%boot-done from=@p]  bind:m  (check-ship-booted from)
=%  [%booted to=@p]       bind:m  (boot-ship ~dev ~)
=%  [%boot-done to=@p]    bind:m  (check-ship-booted to)
(send-hi ~bud ~dev)
```
This assumes you have defined an explicitly parameterized …

Add =% for monadic operations

---

sys/arvo.hoon
sys/vane/dill.hoon

And slightly tweaks %dill's printing of %crud errors. This is the dual of urbit/urbit#1245

adds Arvo %warn error notification event handler

---

lib/hood/helm.hoon

This now matches [the one in zuse](https://github.com/urbit/arvo/blob/master/sys/zuse.hoon#L1875).
Seems like something that was missed during single-homing?
Curiously, people who hadn't touched their `helm.hoon` were still able to rekey just fine. Only after recompiling `helm.hoon` did they run into problems with this.
(idk where to target this PR anymore)

Update %mint task structure in helm

---

lib/collections.hoon
lib/hall-legacy.hoon
lib/hood/kiln.hoon
lib/oauth1.hoon
lib/oauth2.hoon
lib/test/runner.hoon
mar/collections/action.hoon
sys/arvo.hoon
sys/hoon.hoon
sys/vane/ames.hoon
sys/vane/behn.hoon
sys/vane/clay.hoon
sys/vane/dill.hoon
sys/vane/eyre.hoon
sys/vane/ford.hoon
sys/vane/gall.hoon
sys/vane/jael.hoon
sys/vane/xmas.hoon
sys/zuse.hoon

The previous commit changed the semantics of ;; to just call the mold with the result of the hoon, rather than having it macroexpand to something like hard. By "hard" is meant applying the mold and then checking whether the result is unchanged. This second commit removes the +hard function itself, with the effect that there are no remaining mold "idempotence" tests in the system.
#1055

remove +hard, replace with new ;;

---

app/aqua-eyre.hoon
app/aqua.hoon
app/lens.hoon
lib/hood/drum.hoon
lib/ph/azimuth.hoon
sys/vane/rver.hoon
sys/zuse.hoon

This PR is the dual of urbit/urbit#1277. %rver implements the new %request-local task (thanks @ixv!), and there's an incredibly basic, one-request-at-a-time lens app. Just enough to get the CI and pill staging back to a working state (on urbit/urbit).

lte: restore lens control plane

---

sys/hoon.hoon

This message printed on each recursion of `mint:ut` radically slows down the hoon code, and must be disabled if the hoon implementation is to take the place of the C.

remove ~&pure-mint from mint (prelude to jet decapitation)

---

sys/vane/clay.hoon
tests/sys/vane/clay.hoon

Two changes:
- When sending a note with the clad monad, you may include a path which gets appended on the wire.  This is used exclusively for documentation purposes, to counteract the negative effects of continuation-based programming on inspectability by `|verb`.
- I extracted the essential character of the clad monad's evaluator into a pure function in `+clad`.  Now, `+take:eval:clad` deals with the specifics of the monad (eg accumulating effects, implementing the `%cont` handling that ensures the associativity of `+bind`, etc).  Thus, `+take-commit` and `+take-merge` only have to deal with the imperative parts (fetching the transaction from our global state and writing it back) and the results when the transaction finishes.
Additional generalizations that I expect to happen at some …

Clad improvements

---

app/aqua.hoon
app/ph.hoon
lib/hood/kiln.hoon
lib/pill.hoon
sys/vane/clay.hoon
sys/vane/dill.hoon
sys/zuse.hoon

I'm a programmer today because a man at my church gave me a copy of Linux on a CD when I was a kid and told me to learn C.  He also told me a story of when he was a kid.  There was a small anthill where he was playing in his backyard.  He tried destroying the anthill with a stick, but it kept coming back.  Rather than figure out exactly how to remove this anthill surgically, he poured a flammable liquid (gasoline?  I forget) in the anthill.  He figured he'd pour until it was full, then light it.  But it took a lot longer than he thought, and he poured in a lot of gasoline.  Finally, he lit it, and he says it blew up much of his backyard.  He didn't have ant problems for a long time.
This is the approach I've taken with Clay, both in #1169 and here.  There was some bug in +wake, but that …

Clay cleanup

---

sys/hoon.hoon

The expansions of `$>` and `$<` were infinitely recursive. These are new specs for building molds from parts of other `$%` molds. They are `?>`-style assertions against the head of the noun being cast or nest-checked. For example:
```
> `task:able:ames`[%west ~zod /foo 1]
[%west p=~zod q=/foo r=1]
>
> `$>(%west task:able:ames)`[%west ~zod /foo 1]
[%west p=~zod q=/foo r=1]
> 
> `$<(%west task:able:ames)`[%west ~zod /foo 1]
nest-fail
```
I think it would be very helpful to use these specs when building the `+note` and `+sign` molds for vanes, which are obviously subtypes of the `+task` and `+gift` types of the other vanes in the system. If there's interest, I'd be happy to do so now.

fixes the macro expansion of $> and $< specs

---

sys/hoon.hoon

This PR fixes higher-order molds (ie, `+*` specs) in cases where their parameters are bunted. It does so be explicitly defaulting the `$-` to an identity function.
Before:
```
> ((pair) [1 2])
[p=0 q=0]
> ((list) [1 2 3 ~])
~[0 0 0]
> ((tree) (sy 1 2 3 ~))
{0 0 0}
```
After:
```
> ((pair) [1 2])
[p=1 q=2]
> ((list) [1 2 3 ~])
~[1 2 3]
> ((tree) (sy 1 2 3 ~))
{1 2 3}
```

fix higher-order mold parameter-bunts

---

sys/vane/ames.hoon
sys/vane/behn.hoon
sys/vane/clay.hoon
sys/vane/dill.hoon
sys/vane/eyre.hoon
sys/vane/ford.hoon
sys/vane/jael.hoon
sys/zuse.hoon
tests/sys/vane/jael.hoon

This PR uses `$>` (fixed in #1176) to deduplicate the `+note` (outgoing "request") and `+sign` (incoming "response") interfaces of all the vanes, defining these interfaces in terms of the `+task` (incoming "request") and `+gift` (outgoing "response") interfaces of other vanes wherever possible. 
I've also moved all the `+note`/`+sign` definitions into the vanes themselves  -- some were previously in %zuse, but there's no reason for anything but the vanes (and their tests) to reference these.

deduplicates vane interfaces (+note/+sign)

---

sys/vane/gall.hoon

Suppose `my-mark` has type `my-type`.
In gall apps, `+diff-my-mark` handles all `%diff` cards with mark `my-mark` and takes an argument of type `[wire my-type]`.
However, `+diff` handles all `%diff` cards not otherwise handled, and takes an argument of type `[wire cage]`.  A `cage` includes `vase`, which is very unhelpful (so it was never used).
This is obviously wrong.  This PR makes it so `+diff` takes an argument of type `[wire %my-mark my-type]`.  This gives us a well-typed value, so we can actually do something with this.
The same applies to `+sigh`, so I changed that too.
The motivation for this is in the `philip/trad` branch, where I would like to be able to handle all subscription results in a single arm because the library that creates this arm doesn't know until compile time …

More useful +diff and +sigh in gall apps

---

sys/hoon.hoon

This one -- presumably a typo, unless I deeply misunderstand something -- has been annoying me for awhile.
(Note, if it's not immediately obvious: this one is in the body of `+nest`, not `+nets`.)

Replace errant nets-need with nest-need in error message.

---

app/example-tapp-fetch.hoon
app/example-tapp-subscribe.hoon
lib/async.hoon
lib/stdio.hoon
lib/tapp.hoon

I really feel like "async" is exactly the right name for the "trad" monad.  It's an "asynchronous computation" or an "asynchronous transaction".
I'm not super happy with "tapp" for "transacting app", but I haven't come up with anything better.  "Blocking app" is more descriptive but long.  "Block" is cute and suggests LEGO blocks that can be combined easily and safely, but it's a very generic word.

trad -> async

---

app/acme.hoon

This fixes a (dumb) bug I introduced when refactoring the ACME (LetsEncrypt) client.
Signed ACME requests include an anti-replay nonce, which implies server state. Previously-good nonces retrieved from ACME can become "bad" if the server-state in question goes away for some reason. Since any request can produce a "bad-nonce" response, robust clients must be able to intercept this error condition, retrieve a fresh nonce, and then "retry" their request (this makes for some pretty complicated control flow in our explicit state machines). The bug in this case was simply not passing the name of the action to take after retrieving a nonce. The symptom is an :acme app crash with `%bad-nonce-next` in the stack trace.
This is a good candidate for an OTA hotfix release.
/cc @galenwp

fixes :acme retry on "bad-nonce" error

---

sys/hoon.hoon

This commit fixes a jet mismatch in nest:ut. Recall that "iron" cores are meant to be contravariant in their sample, while "zinc" cores are covariant. This behavior is correctly implemented on lines 191-200 and 204-214 of ut_nest.c: the order of arguments passed to dext (and therefore the orientation of the subtyping check) is swapped between these two cases. Unfortunately, the code in hoon.hoon forgets to do this and treats iron cores as though they were zinc.
I would like to say that this closes the matter of the nest jet, but it does not. With this change applied, and nest decapitated, a ship now runs out of memory whenever it recompiles itself. Previously, a nest-decapitated binary would give rise to "type errors" on these operations. Currently, I believe this is a case of one problem …

fix hoon.hoon nest: make %iron different from %zinc

---

app/example-tapp-fetch.hoon
gen/tapp-admin/cancel.hoon
gen/tapp-admin/restart.hoon
lib/async.hoon
lib/stdio.hoon
lib/tapp.hoon
sur/tapp.hoon
sys/vane/ames.hoon
sys/vane/gall.hoon
sys/vane/lient.hoon
sys/zuse.hoon

This PR is the first half of #1194, ported onto lighter-than-eyre. (The second half is incoming but will take more time, specifically with regards to the bespoke oauth2 implementation in the GCP DNS integration.)
This also fixes a bug in the `%lient` http-connection cleanup, and refactors the %rver and %lient interface declarations.

ports async/tapp/stdio to lighter-than-eyre
